/**
 * The verified product numbers shown on the marketing landing page.
 *
 * Read from `packages/registry/dist/stats.json` (generated by `pnpm registry:build`, see
 * `packages/registry/src/build.ts`) rather than hard-coded, so they cannot drift from the real
 * registry. Mirrors the approach the previous `~/components/landing/content.ts` used.
 */
import registryStats from "../../../../packages/registry/dist/stats.json";

/** "797 Registry entries" — every registry item of any type. */
export const REGISTRY_ENTRIES = registryStats.entries;

/** "69 Published component groups" — base + application + marketing layers. */
export const PUBLISHED_GROUPS = registryStats.groups.published;

/** "679 Composable variants" — marketing section variants plus full-page examples. */
export const COMPOSABLE_VARIANTS = registryStats.variants + registryStats.examples.total;

/** "19 Base components". */
export const BASE_COMPONENTS = registryStats.groups.byLayer.base;

/** "32 Application groups". */
export const APPLICATION_GROUPS = registryStats.groups.byLayer.application;

/** "18 Marketing sections". */
export const MARKETING_SECTIONS = registryStats.groups.byLayer.marketing;

/** "233 Full-page examples" — marketing-examples + app-examples layers together. */
export const PAGE_EXAMPLES = registryStats.examples.total;

/** "118 axe suites" — one per component, each asserting zero violations. */
export const AXE_SUITES = registryStats.axeSuites;

/** "0 Detected axe violations" — not a stats.json field: it is definitionally zero whenever the axe suites above are green. */
export const AXE_VIOLATIONS = 0;

/** "13 Flows": ordered multi-screen journeys in the registry. Zero until `stats.json` carries the field. */
export const FLOWS = (registryStats as { flows?: number }).flows ?? 0;

/** "679 Thumbnails": rendered preview images in the registry. Zero until `stats.json` carries the field. */
export const THUMBNAILS = (registryStats as { thumbnails?: number }).thumbnails ?? 0;
