// GENERATED FILE — do not edit by hand. Run `pnpm gen:demos`.
import type { ComponentType } from "react";
import * as d0 from "@properui/ui/components/app-examples/404-sections/404-sections.demo";
import * as d1 from "@properui/ui/components/app-examples/dashboards-02/dashboards-02.demo";
import * as d2 from "@properui/ui/components/app-examples/dashboards/dashboards.demo";
import * as d3 from "@properui/ui/components/app-examples/email-templates/email-templates.demo";
import * as d4 from "@properui/ui/components/app-examples/forgot-password-pages/forgot-password-pages.demo";
import * as d5 from "@properui/ui/components/app-examples/informational-pages-02/informational-pages-02.demo";
import * as d6 from "@properui/ui/components/app-examples/informational-pages/informational-pages.demo";
import * as d7 from "@properui/ui/components/app-examples/log-in-pages/log-in-pages.demo";
import * as d8 from "@properui/ui/components/app-examples/settings-pages-02/settings-pages-02.demo";
import * as d9 from "@properui/ui/components/app-examples/settings-pages/settings-pages.demo";
import * as d10 from "@properui/ui/components/app-examples/sign-up-pages/sign-up-pages.demo";
import * as d11 from "@properui/ui/components/app-examples/verification-pages/verification-pages.demo";
import * as d12 from "@properui/ui/components/application/activity-feed/activity-feed.demo";
import * as d13 from "@properui/ui/components/application/alerts/alerts.demo";
import * as d14 from "@properui/ui/components/application/app-navigation/header-navigation.demo";
import * as d15 from "@properui/ui/components/application/app-navigation/sidebar-navigation.demo";
import * as d16 from "@properui/ui/components/application/breadcrumbs/breadcrumbs.demo";
import * as d17 from "@properui/ui/components/application/callout/callout.demo";
import * as d18 from "@properui/ui/components/application/card-headers/card-headers.demo";
import * as d19 from "@properui/ui/components/application/carousel/carousel.demo";
import * as d20 from "@properui/ui/components/application/charts/activity-gauges.demo";
import * as d21 from "@properui/ui/components/application/charts/line-bar-charts.demo";
import * as d22 from "@properui/ui/components/application/charts/pie-charts.demo";
import * as d23 from "@properui/ui/components/application/charts/radar-charts.demo";
import * as d24 from "@properui/ui/components/application/code-editor/code-editor.demo";
import * as d25 from "@properui/ui/components/application/code-snippet/code-snippet.demo";
import * as d26 from "@properui/ui/components/application/color-picker/color-picker.demo";
import * as d27 from "@properui/ui/components/application/command-menu/command-menu.demo";
import * as d28 from "@properui/ui/components/application/confirm-dialog/confirm-dialog.demo";
import * as d29 from "@properui/ui/components/application/content-divider/content-divider.demo";
import * as d30 from "@properui/ui/components/application/date-picker/calendar.demo";
import * as d31 from "@properui/ui/components/application/date-picker/date-pickers.demo";
import * as d32 from "@properui/ui/components/application/description-list/description-list.demo";
import * as d33 from "@properui/ui/components/application/empty-state/empty-state.demo";
import * as d34 from "@properui/ui/components/application/file-upload/file-upload.demo";
import * as d35 from "@properui/ui/components/application/filter-bar/filter-bars.demo";
import * as d36 from "@properui/ui/components/application/gantt/gantt.demo";
import * as d37 from "@properui/ui/components/application/gradient-picker/gradient-picker.demo";
import * as d38 from "@properui/ui/components/application/image-picker/image-picker.demo";
import * as d39 from "@properui/ui/components/application/inline-cta/inline-cta.demo";
import * as d40 from "@properui/ui/components/application/kanban/kanban.demo";
import * as d41 from "@properui/ui/components/application/loading-indicator/loading-indicator.demo";
import * as d42 from "@properui/ui/components/application/messaging/messaging.demo";
import * as d43 from "@properui/ui/components/application/metrics/metrics.demo";
import * as d44 from "@properui/ui/components/application/modals/modals.demo";
import * as d45 from "@properui/ui/components/application/notifications/notifications.demo";
import * as d46 from "@properui/ui/components/application/page-headers/page-headers.demo";
import * as d47 from "@properui/ui/components/application/pagination/pagination.demo";
import * as d48 from "@properui/ui/components/application/progress-steps/progress-steps.demo";
import * as d49 from "@properui/ui/components/application/resizable/resizable.demo";
import * as d50 from "@properui/ui/components/application/scroll-area/scroll-area.demo";
import * as d51 from "@properui/ui/components/application/section-footers/section-footers.demo";
import * as d52 from "@properui/ui/components/application/section-headers/section-headers.demo";
import * as d53 from "@properui/ui/components/application/slideout-menus/slideout-menus.demo";
import * as d54 from "@properui/ui/components/application/sortable-list/sortable-list.demo";
import * as d55 from "@properui/ui/components/application/stepper/stepper.demo";
import * as d56 from "@properui/ui/components/application/table/table.demo";
import * as d57 from "@properui/ui/components/application/tabs/tabs.demo";
import * as d58 from "@properui/ui/components/application/timeline/timeline.demo";
import * as d59 from "@properui/ui/components/application/tree-view/tree-view.demo";
import * as d60 from "@properui/ui/components/base/avatar/avatar.demo";
import * as d61 from "@properui/ui/components/base/badges/badge-groups.demo";
import * as d62 from "@properui/ui/components/base/badges/badges.demo";
import * as d63 from "@properui/ui/components/base/button-group/button-group.demo";
import * as d64 from "@properui/ui/components/base/buttons/app-store-buttons.demo";
import * as d65 from "@properui/ui/components/base/buttons/button-utility.demo";
import * as d66 from "@properui/ui/components/base/buttons/buttons.demo";
import * as d67 from "@properui/ui/components/base/buttons/social-buttons.demo";
import * as d68 from "@properui/ui/components/base/checkbox/checkbox.demo";
import * as d69 from "@properui/ui/components/base/dropdown/context-menus.demo";
import * as d70 from "@properui/ui/components/base/dropdown/dropdown.demo";
import * as d71 from "@properui/ui/components/base/hover-card/hover-card.demo";
import * as d72 from "@properui/ui/components/base/input/inputs.demo";
import * as d73 from "@properui/ui/components/base/input/pin-input.demo";
import * as d74 from "@properui/ui/components/base/menubar/menubar.demo";
import * as d75 from "@properui/ui/components/base/number-input/number-input.demo";
import * as d76 from "@properui/ui/components/base/popover/popover.demo";
import * as d77 from "@properui/ui/components/base/progress-indicators/progress-indicators.demo";
import * as d78 from "@properui/ui/components/base/radio-buttons/radio-buttons.demo";
import * as d79 from "@properui/ui/components/base/select/multi-select.demo";
import * as d80 from "@properui/ui/components/base/select/select.demo";
import * as d81 from "@properui/ui/components/base/skeleton/skeleton.demo";
import * as d82 from "@properui/ui/components/base/slider/slider.demo";
import * as d83 from "@properui/ui/components/base/tag-input/tag-input.demo";
import * as d84 from "@properui/ui/components/base/tags/tags.demo";
import * as d85 from "@properui/ui/components/base/text-editor/text-editor.demo";
import * as d86 from "@properui/ui/components/base/textarea/textarea.demo";
import * as d87 from "@properui/ui/components/base/toggle-chip/toggle-chip.demo";
import * as d88 from "@properui/ui/components/base/toggle/toggle.demo";
import * as d89 from "@properui/ui/components/base/tooltip/tooltip.demo";
import * as d90 from "@properui/ui/components/base/video-player/video-player.demo";
import * as d91 from "@properui/ui/components/foundations/featured-icon/featured-icon.demo";
import * as d92 from "@properui/ui/components/foundations/rating/rating.demo";
import * as d93 from "@properui/ui/components/foundations/typography/typography.demo";
import * as d94 from "@properui/ui/components/marketing-examples/404-pages/404-pages.demo";
import * as d95 from "@properui/ui/components/marketing-examples/about-pages/about-pages.demo";
import * as d96 from "@properui/ui/components/marketing-examples/blog-pages/blog-pages.demo";
import * as d97 from "@properui/ui/components/marketing-examples/blog-post-pages/blog-post-pages.demo";
import * as d98 from "@properui/ui/components/marketing-examples/contact-pages/contact-pages.demo";
import * as d99 from "@properui/ui/components/marketing-examples/faq-pages/faq-pages.demo";
import * as d100 from "@properui/ui/components/marketing-examples/landing-pages/landing-pages.demo";
import * as d101 from "@properui/ui/components/marketing-examples/legal-pages/legal-pages.demo";
import * as d102 from "@properui/ui/components/marketing-examples/pricing-pages/pricing-pages.demo";
import * as d103 from "@properui/ui/components/marketing-examples/team-pages/team-pages.demo";
import * as d104 from "@properui/ui/components/marketing/banners/banners.demo";
import * as d105 from "@properui/ui/components/marketing/blog-sections/blog-sections.demo";
import * as d106 from "@properui/ui/components/marketing/careers-sections/careers-sections.demo";
import * as d107 from "@properui/ui/components/marketing/contact-sections/contact-sections.demo";
import * as d108 from "@properui/ui/components/marketing/content-rich-text-sections/content-rich-text-sections.demo";
import * as d109 from "@properui/ui/components/marketing/cta-sections/cta-sections.demo";
import * as d110 from "@properui/ui/components/marketing/faq-sections/faq-sections.demo";
import * as d111 from "@properui/ui/components/marketing/features-sections/features-sections.demo";
import * as d112 from "@properui/ui/components/marketing/footers/footers.demo";
import * as d113 from "@properui/ui/components/marketing/header-navigations/header-navigations.demo";
import * as d114 from "@properui/ui/components/marketing/header-sections/header-sections.demo";
import * as d115 from "@properui/ui/components/marketing/hero-header-sections/hero-header-sections.demo";
import * as d116 from "@properui/ui/components/marketing/metrics-sections/metrics-sections.demo";
import * as d117 from "@properui/ui/components/marketing/newsletter-cta-sections/newsletter-cta-sections.demo";
import * as d118 from "@properui/ui/components/marketing/pricing-sections/pricing-sections.demo";
import * as d119 from "@properui/ui/components/marketing/social-proof-sections/social-proof-sections.demo";
import * as d120 from "@properui/ui/components/marketing/team-sections/team-sections.demo";
import * as d121 from "@properui/ui/components/marketing/testimonial-sections/testimonial-sections.demo";
import * as d122 from "@properui/ui/components/shared-assets/credit-card/credit-card.demo";
import * as d123 from "@properui/ui/components/shared-assets/illustrations/illustrations.demo";
import * as d124 from "@properui/ui/components/shared-assets/qr-code/qr-code.demo";

export const demos: Record<string, ComponentType> = {
    "404-sections:Section404Example": d0.Section404Example as ComponentType,
    "dashboards-02:DashboardWithHeaderNavigationExample": d1.DashboardWithHeaderNavigationExample as ComponentType,
    "dashboards:DashboardWithSidebarNavigationExample": d2.DashboardWithSidebarNavigationExample as ComponentType,
    "email-templates:EmailTemplateExample": d3.EmailTemplateExample as ComponentType,
    "forgot-password-pages:ForgotPasswordPageExample": d4.ForgotPasswordPageExample as ComponentType,
    "informational-pages-02:InformationalPageWithHeaderNavigationExample": d5.InformationalPageWithHeaderNavigationExample as ComponentType,
    "informational-pages:InformationalPageWithSidebarNavigationExample": d6.InformationalPageWithSidebarNavigationExample as ComponentType,
    "log-in-pages:LogInPageExample": d7.LogInPageExample as ComponentType,
    "settings-pages-02:SettingsPageWithHeaderNavigationExample": d8.SettingsPageWithHeaderNavigationExample as ComponentType,
    "settings-pages:SettingsPageWithSidebarNavigationExample": d9.SettingsPageWithSidebarNavigationExample as ComponentType,
    "sign-up-pages:SignUpPageExample": d10.SignUpPageExample as ComponentType,
    "verification-pages:VerificationPageExample": d11.VerificationPageExample as ComponentType,
    "activity-feed:ActivityFeedExample": d12.ActivityFeedExample as ComponentType,
    "activity-feed:ActivityFeedDivided": d12.ActivityFeedDivided as ComponentType,
    "activity-feed:ActivityFeedConnected": d12.ActivityFeedConnected as ComponentType,
    "activity-feed:ActivityFeedSpaced": d12.ActivityFeedSpaced as ComponentType,
    "activity-feed:MessagesDivided": d12.MessagesDivided as ComponentType,
    "activity-feed:MessagesConnected": d12.MessagesConnected as ComponentType,
    "activity-feed:MessagesSpaced": d12.MessagesSpaced as ComponentType,
    "alerts:AlertExample": d13.AlertExample as ComponentType,
    "alerts:FloatingDefault": d13.FloatingDefault as ComponentType,
    "alerts:FloatingBrand": d13.FloatingBrand as ComponentType,
    "alerts:FloatingGray": d13.FloatingGray as ComponentType,
    "alerts:FloatingError": d13.FloatingError as ComponentType,
    "alerts:FloatingWarning": d13.FloatingWarning as ComponentType,
    "alerts:FloatingSuccess": d13.FloatingSuccess as ComponentType,
    "alerts:FullWidthDefault": d13.FullWidthDefault as ComponentType,
    "alerts:FullWidthBrand": d13.FullWidthBrand as ComponentType,
    "alerts:FullWidthGray": d13.FullWidthGray as ComponentType,
    "alerts:FullWidthError": d13.FullWidthError as ComponentType,
    "alerts:FullWidthWarning": d13.FullWidthWarning as ComponentType,
    "alerts:FullWidthSuccess": d13.FullWidthSuccess as ComponentType,
    "header-navigation:HeaderNavigationExample": d14.HeaderNavigationExample as ComponentType,
    "header-navigation:Simple": d14.Simple as ComponentType,
    "header-navigation:DualTier": d14.DualTier as ComponentType,
    "sidebar-navigation:SidebarNavigationExample": d15.SidebarNavigationExample as ComponentType,
    "sidebar-navigation:Simple": d15.Simple as ComponentType,
    "sidebar-navigation:CustomBrand": d15.CustomBrand as ComponentType,
    "sidebar-navigation:DualTier": d15.DualTier as ComponentType,
    "sidebar-navigation:Slim": d15.Slim as ComponentType,
    "sidebar-navigation:SectionsDividers": d15.SectionsDividers as ComponentType,
    "sidebar-navigation:SectionsSubheadings": d15.SectionsSubheadings as ComponentType,
    "sidebar-navigation:ProgressBar": d15.ProgressBar as ComponentType,
    "sidebar-navigation:ProgressCircle": d15.ProgressCircle as ComponentType,
    "sidebar-navigation:Image": d15.Image as ComponentType,
    "sidebar-navigation:CookiePreferences": d15.CookiePreferences as ComponentType,
    "sidebar-navigation:ReferralLink": d15.ReferralLink as ComponentType,
    "sidebar-navigation:OnboardingSteps": d15.OnboardingSteps as ComponentType,
    "sidebar-navigation:UpgradeCTA": d15.UpgradeCTA as ComponentType,
    "sidebar-navigation:SupportCTA": d15.SupportCTA as ComponentType,
    "sidebar-navigation:EventCTA": d15.EventCTA as ComponentType,
    "sidebar-navigation:Message": d15.Message as ComponentType,
    "sidebar-navigation:CurrentProjects": d15.CurrentProjects as ComponentType,
    "sidebar-navigation:FreeTrialCTA": d15.FreeTrialCTA as ComponentType,
    "sidebar-navigation:QRCode": d15.QRCode as ComponentType,
    "breadcrumbs:BreadcrumbsExample": d16.BreadcrumbsExample as ComponentType,
    "breadcrumbs:BreadcrumbsText": d16.BreadcrumbsText as ComponentType,
    "breadcrumbs:BreadcrumbsTextWithLine": d16.BreadcrumbsTextWithLine as ComponentType,
    "breadcrumbs:BreadcrumbsButton": d16.BreadcrumbsButton as ComponentType,
    "breadcrumbs:AccountButtonChevron": d16.AccountButtonChevron as ComponentType,
    "breadcrumbs:AccountButtonSlash": d16.AccountButtonSlash as ComponentType,
    "callout:CalloutExample": d17.CalloutExample as ComponentType,
    "callout:Tones": d17.Tones as ComponentType,
    "callout:WithoutTitle": d17.WithoutTitle as ComponentType,
    "callout:WithoutIcon": d17.WithoutIcon as ComponentType,
    "card-headers:CardHeaderExample": d18.CardHeaderExample as ComponentType,
    "card-headers:CardHeaderWithBadge": d18.CardHeaderWithBadge as ComponentType,
    "card-headers:CardHeaderWithAvatarAndBadge": d18.CardHeaderWithAvatarAndBadge as ComponentType,
    "carousel:CarouselExample": d19.CarouselExample as ComponentType,
    "carousel:CarouselMd": d19.CarouselMd as ComponentType,
    "carousel:CarouselLg": d19.CarouselLg as ComponentType,
    "activity-gauges:ActivityGaugeXs": d20.ActivityGaugeXs as ComponentType,
    "activity-gauges:ActivityGaugeSm": d20.ActivityGaugeSm as ComponentType,
    "activity-gauges:ActivityGaugeMd": d20.ActivityGaugeMd as ComponentType,
    "activity-gauges:ActivityGaugeLg": d20.ActivityGaugeLg as ComponentType,
    "activity-gauges:ActivityGaugeExample": d20.ActivityGaugeExample as ComponentType,
    "line-bar-charts:LineChart01": d21.LineChart01 as ComponentType,
    "line-bar-charts:LineChart02": d21.LineChart02 as ComponentType,
    "line-bar-charts:LineChart03": d21.LineChart03 as ComponentType,
    "line-bar-charts:LineChart04": d21.LineChart04 as ComponentType,
    "line-bar-charts:BarChart01": d21.BarChart01 as ComponentType,
    "line-bar-charts:BarChart02": d21.BarChart02 as ComponentType,
    "line-bar-charts:BarChart03": d21.BarChart03 as ComponentType,
    "line-bar-charts:LineChartExample": d21.LineChartExample as ComponentType,
    "pie-charts:PieChartXxl": d22.PieChartXxl as ComponentType,
    "pie-charts:PieChartXs": d22.PieChartXs as ComponentType,
    "pie-charts:PieChartSm": d22.PieChartSm as ComponentType,
    "pie-charts:PieChartMd": d22.PieChartMd as ComponentType,
    "pie-charts:PieChartLg": d22.PieChartLg as ComponentType,
    "pie-charts:PieChartExample": d22.PieChartExample as ComponentType,
    "radar-charts:RadarChart": d23.RadarChart as ComponentType,
    "radar-charts:RadarChartExample": d23.RadarChartExample as ComponentType,
    "code-editor:CodeEditorExample": d24.CodeEditorExample as ComponentType,
    "code-editor:JsonEditor": d24.JsonEditor as ComponentType,
    "code-editor:ReadOnlyWithDiagnostics": d24.ReadOnlyWithDiagnostics as ComponentType,
    "code-editor:Minimal": d24.Minimal as ComponentType,
    "code-snippet:CodeSnippetExample": d25.CodeSnippetExample as ComponentType,
    "code-snippet:WithLineNumber": d25.WithLineNumber as ComponentType,
    "code-snippet:WithoutLineNumber": d25.WithoutLineNumber as ComponentType,
    "code-snippet:ShowMore": d25.ShowMore as ComponentType,
    "code-snippet:WithTabs": d25.WithTabs as ComponentType,
    "color-picker:ColorPickerExample": d26.ColorPickerExample as ComponentType,
    "color-picker:ColorPicker": d26.ColorPicker as ComponentType,
    "color-picker:ColorSwatchPicker": d26.ColorSwatchPicker as ComponentType,
    "color-picker:SavedSwatchesSmall": d26.SavedSwatchesSmall as ComponentType,
    "color-picker:SavedSwatchesMedium": d26.SavedSwatchesMedium as ComponentType,
    "color-picker:BrandSwatches": d26.BrandSwatches as ComponentType,
    "color-picker:GraySwatches": d26.GraySwatches as ComponentType,
    "color-picker:MinimalPicker": d26.MinimalPicker as ComponentType,
    "color-picker:HueSlider": d26.HueSlider as ComponentType,
    "color-picker:TransparencySlider": d26.TransparencySlider as ComponentType,
    "color-picker:PalettePicker": d26.PalettePicker as ComponentType,
    "command-menu:CommandMenuExample": d27.CommandMenuExample as ComponentType,
    "command-menu:Users": d27.Users as ComponentType,
    "command-menu:UsersStacked": d27.UsersStacked as ComponentType,
    "command-menu:Actions": d27.Actions as ComponentType,
    "command-menu:ActionsStacked": d27.ActionsStacked as ComponentType,
    "command-menu:EmptyState": d27.EmptyState as ComponentType,
    "command-menu:UsersMenu": d27.UsersMenu as ComponentType,
    "command-menu:UsersMenuStacked": d27.UsersMenuStacked as ComponentType,
    "command-menu:IntegrationsMenu": d27.IntegrationsMenu as ComponentType,
    "command-menu:IntegrationsMenuStacked": d27.IntegrationsMenuStacked as ComponentType,
    "confirm-dialog:ConfirmDialogExample": d28.ConfirmDialogExample as ComponentType,
    "confirm-dialog:Destructive": d28.Destructive as ComponentType,
    "confirm-dialog:AsyncConfirm": d28.AsyncConfirm as ComponentType,
    "content-divider:ContentDividerExample": d29.ContentDividerExample as ComponentType,
    "content-divider:SingleLine": d29.SingleLine as ComponentType,
    "content-divider:DualLine": d29.DualLine as ComponentType,
    "content-divider:BackgroundFill": d29.BackgroundFill as ComponentType,
    "calendar:CalendarExample": d30.CalendarExample as ComponentType,
    "calendar:CalendarMonthView": d30.CalendarMonthView as ComponentType,
    "calendar:CalendarWeekView": d30.CalendarWeekView as ComponentType,
    "calendar:CalendarDayView": d30.CalendarDayView as ComponentType,
    "date-pickers:DatePickerExample": d31.DatePickerExample as ComponentType,
    "date-pickers:DatePicker": d31.DatePicker as ComponentType,
    "date-pickers:DateTimePicker": d31.DateTimePicker as ComponentType,
    "date-pickers:DateRangePickerWithPresets": d31.DateRangePickerWithPresets as ComponentType,
    "date-pickers:Calendar": d31.Calendar as ComponentType,
    "date-pickers:CalendarCard": d31.CalendarCard as ComponentType,
    "date-pickers:RangeCalendar": d31.RangeCalendar as ComponentType,
    "date-pickers:RangeCalendarCard": d31.RangeCalendarCard as ComponentType,
    "description-list:DescriptionListExample": d32.DescriptionListExample as ComponentType,
    "description-list:Horizontal": d32.Horizontal as ComponentType,
    "description-list:Stacked": d32.Stacked as ComponentType,
    "empty-state:EmptyStateExample": d33.EmptyStateExample as ComponentType,
    "empty-state:FeaturedIcon": d33.FeaturedIcon as ComponentType,
    "empty-state:Illustration": d33.Illustration as ComponentType,
    "empty-state:FileIcon": d33.FileIcon as ComponentType,
    "empty-state:AvatarRadius": d33.AvatarRadius as ComponentType,
    "empty-state:AvatarRow": d33.AvatarRow as ComponentType,
    "empty-state:AvatarGrid": d33.AvatarGrid as ComponentType,
    "file-upload:FileUploadExample": d34.FileUploadExample as ComponentType,
    "file-upload:ProgressBar": d34.ProgressBar as ComponentType,
    "file-upload:ProgressFill": d34.ProgressFill as ComponentType,
    "file-upload:Disabled": d34.Disabled as ComponentType,
    "file-upload:AcceptImageOnly": d34.AcceptImageOnly as ComponentType,
    "file-upload:MaxSizeLimit": d34.MaxSizeLimit as ComponentType,
    "filter-bars:FilterBarExample": d35.FilterBarExample as ComponentType,
    "filter-bars:Simple": d35.Simple as ComponentType,
    "filter-bars:TabsAndSearch": d35.TabsAndSearch as ComponentType,
    "filter-bars:TabsAndDatePicker": d35.TabsAndDatePicker as ComponentType,
    "filter-bars:DateFilters": d35.DateFilters as ComponentType,
    "filter-bars:Dropdowns": d35.Dropdowns as ComponentType,
    "filter-bars:DropdownsAndDatePicker": d35.DropdownsAndDatePicker as ComponentType,
    "filter-bars:AdvancedFilterInactive": d35.AdvancedFilterInactive as ComponentType,
    "filter-bars:AdvancedFilterActive": d35.AdvancedFilterActive as ComponentType,
    "filter-bars:FilterDropdownEmptyState": d35.FilterDropdownEmptyState as ComponentType,
    "filter-bars:FilterDropdownInactive": d35.FilterDropdownInactive as ComponentType,
    "filter-bars:FilterDropdownActive": d35.FilterDropdownActive as ComponentType,
    "filter-bars:FiltersAdvancedEmptyStateMenu": d35.FiltersAdvancedEmptyStateMenu as ComponentType,
    "filter-bars:FiltersAdvancedActiveMenu": d35.FiltersAdvancedActiveMenu as ComponentType,
    "gantt:GanttExample": d36.GanttExample as ComponentType,
    "gantt:DayZoom": d36.DayZoom as ComponentType,
    "gantt:MonthZoomWithMarkers": d36.MonthZoomWithMarkers as ComponentType,
    "gantt:ReadOnly": d36.ReadOnly as ComponentType,
    "gradient-picker:GradientPickerExample": d37.GradientPickerExample as ComponentType,
    "gradient-picker:GradientPicker": d37.GradientPicker as ComponentType,
    "image-picker:ImagePickerExample": d38.ImagePickerExample as ComponentType,
    "image-picker:ImagePicker": d38.ImagePicker as ComponentType,
    "inline-cta:InlineCTAExample": d39.InlineCTAExample as ComponentType,
    "inline-cta:Actions": d39.Actions as ComponentType,
    "inline-cta:EmailField": d39.EmailField as ComponentType,
    "inline-cta:ChangePlan": d39.ChangePlan as ComponentType,
    "inline-cta:UpgradePlan": d39.UpgradePlan as ComponentType,
    "inline-cta:PaymentMethod": d39.PaymentMethod as ComponentType,
    "inline-cta:Receipt": d39.Receipt as ComponentType,
    "kanban:KanbanExample": d40.KanbanExample as ComponentType,
    "kanban:CustomCards": d40.CustomCards as ComponentType,
    "kanban:CollapsibleColumns": d40.CollapsibleColumns as ComponentType,
    "loading-indicator:LoadingIndicatorExample": d41.LoadingIndicatorExample as ComponentType,
    "loading-indicator:LineSimple": d41.LineSimple as ComponentType,
    "loading-indicator:LineSimpleWithLabel": d41.LineSimpleWithLabel as ComponentType,
    "loading-indicator:LineSpinner": d41.LineSpinner as ComponentType,
    "loading-indicator:LineSpinnerWithLabel": d41.LineSpinnerWithLabel as ComponentType,
    "loading-indicator:DotCircle": d41.DotCircle as ComponentType,
    "loading-indicator:DotCircleWithLabel": d41.DotCircleWithLabel as ComponentType,
    "loading-indicator:Sizes": d41.Sizes as ComponentType,
    "loading-indicator:InlineXs": d41.InlineXs as ComponentType,
    "messaging:MessagingExample": d42.MessagingExample as ComponentType,
    "messaging:MessageStatus": d42.MessageStatus as ComponentType,
    "messaging:MessageActionMinimal": d42.MessageActionMinimal as ComponentType,
    "messaging:MessageActionTextarea": d42.MessageActionTextarea as ComponentType,
    "messaging:MessageActionAdvanced": d42.MessageActionAdvanced as ComponentType,
    "messaging:MessageSimple": d42.MessageSimple as ComponentType,
    "messaging:MessageReactions": d42.MessageReactions as ComponentType,
    "messaging:MessageReply": d42.MessageReply as ComponentType,
    "messaging:MessageAttachment": d42.MessageAttachment as ComponentType,
    "messaging:MessageAudio": d42.MessageAudio as ComponentType,
    "messaging:MessageImage": d42.MessageImage as ComponentType,
    "messaging:MessageLinkPreview": d42.MessageLinkPreview as ComponentType,
    "messaging:MessageLinkMinimal": d42.MessageLinkMinimal as ComponentType,
    "messaging:MessageWriting": d42.MessageWriting as ComponentType,
    "metrics:MetricsExample": d43.MetricsExample as ComponentType,
    "metrics:Simple": d43.Simple as ComponentType,
    "metrics:SimpleNoChange": d43.SimpleNoChange as ComponentType,
    "metrics:SimpleActions": d43.SimpleActions as ComponentType,
    "metrics:MetricsIcon01": d43.MetricsIcon01 as ComponentType,
    "metrics:MetricsIconActions01": d43.MetricsIconActions01 as ComponentType,
    "metrics:MetricsIcon02": d43.MetricsIcon02 as ComponentType,
    "metrics:MetricsIconActions02": d43.MetricsIconActions02 as ComponentType,
    "metrics:MetricsIcon03": d43.MetricsIcon03 as ComponentType,
    "metrics:MetricsIconActions03": d43.MetricsIconActions03 as ComponentType,
    "metrics:MetricsIcon04": d43.MetricsIcon04 as ComponentType,
    "metrics:MetricsIconActions04": d43.MetricsIconActions04 as ComponentType,
    "metrics:Chart01": d43.Chart01 as ComponentType,
    "metrics:ChartActions01": d43.ChartActions01 as ComponentType,
    "metrics:Chart02": d43.Chart02 as ComponentType,
    "metrics:ChartActions02": d43.ChartActions02 as ComponentType,
    "metrics:Chart03": d43.Chart03 as ComponentType,
    "metrics:ChartActions03": d43.ChartActions03 as ComponentType,
    "metrics:Chart04": d43.Chart04 as ComponentType,
    "metrics:ChartActions04": d43.ChartActions04 as ComponentType,
    "modals:ModalExample": d44.ModalExample as ComponentType,
    "modals:StackedLeftAligned": d44.StackedLeftAligned as ComponentType,
    "modals:WarningStackedLeftAligned": d44.WarningStackedLeftAligned as ComponentType,
    "modals:DestructiveStackedLeftAligned": d44.DestructiveStackedLeftAligned as ComponentType,
    "modals:ConfirmDialog": d44.ConfirmDialog as ComponentType,
    "modals:Horizontal": d44.Horizontal as ComponentType,
    "modals:WarningHorizontal": d44.WarningHorizontal as ComponentType,
    "modals:DestructiveHorizontal": d44.DestructiveHorizontal as ComponentType,
    "modals:Login": d44.Login as ComponentType,
    "modals:Signup01": d44.Signup01 as ComponentType,
    "modals:Signup02": d44.Signup02 as ComponentType,
    "modals:Checkboxes": d44.Checkboxes as ComponentType,
    "modals:Toggles": d44.Toggles as ComponentType,
    "modals:LinkField": d44.LinkField as ComponentType,
    "modals:Dropdown": d44.Dropdown as ComponentType,
    "modals:InputField": d44.InputField as ComponentType,
    "modals:Labels": d44.Labels as ComponentType,
    "modals:AccessRequest": d44.AccessRequest as ComponentType,
    "modals:EmailInvite": d44.EmailInvite as ComponentType,
    "modals:UserInvite": d44.UserInvite as ComponentType,
    "modals:StackedWithTeam": d44.StackedWithTeam as ComponentType,
    "modals:StackedWithTeamAndLink": d44.StackedWithTeamAndLink as ComponentType,
    "modals:StackedWithTeamAndInvites": d44.StackedWithTeamAndInvites as ComponentType,
    "modals:VerificationCode": d44.VerificationCode as ComponentType,
    "modals:TwoFactorCode": d44.TwoFactorCode as ComponentType,
    "modals:PasswordPrompt": d44.PasswordPrompt as ComponentType,
    "modals:CenteredPhoto": d44.CenteredPhoto as ComponentType,
    "modals:CenteredPhotoCarousel": d44.CenteredPhotoCarousel as ComponentType,
    "modals:CenteredVideoCarousel": d44.CenteredVideoCarousel as ComponentType,
    "modals:PaymentDetails": d44.PaymentDetails as ComponentType,
    "modals:PaymentDetailsWithImage": d44.PaymentDetailsWithImage as ComponentType,
    "modals:Plan01": d44.Plan01 as ComponentType,
    "modals:Plan02": d44.Plan02 as ComponentType,
    "modals:PaymentMethod": d44.PaymentMethod as ComponentType,
    "modals:DatePicker": d44.DatePicker as ComponentType,
    "modals:FileUpload": d44.FileUpload as ComponentType,
    "modals:ProfileSettings": d44.ProfileSettings as ComponentType,
    "modals:UserSelection": d44.UserSelection as ComponentType,
    "modals:Form01": d44.Form01 as ComponentType,
    "modals:Form02": d44.Form02 as ComponentType,
    "modals:ImageCrop": d44.ImageCrop as ComponentType,
    "modals:CalendarEvent": d44.CalendarEvent as ComponentType,
    "modals:BannerAppearance": d44.BannerAppearance as ComponentType,
    "modals:AppearanceSettings": d44.AppearanceSettings as ComponentType,
    "modals:AIAssistant": d44.AIAssistant as ComponentType,
    "modals:UserSettings": d44.UserSettings as ComponentType,
    "modals:NewProject": d44.NewProject as ComponentType,
    "modals:TextEditor": d44.TextEditor as ComponentType,
    "modals:ShareProject": d44.ShareProject as ComponentType,
    "modals:CreateEvent": d44.CreateEvent as ComponentType,
    "modals:Integration": d44.Integration as ComponentType,
    "modals:NewMessageEmptyState": d44.NewMessageEmptyState as ComponentType,
    "modals:NewMessageFilled": d44.NewMessageFilled as ComponentType,
    "notifications:NotificationExample": d45.NotificationExample as ComponentType,
    "notifications:IconDefault": d45.IconDefault as ComponentType,
    "notifications:IconGray": d45.IconGray as ComponentType,
    "notifications:IconBrand": d45.IconBrand as ComponentType,
    "notifications:IconError": d45.IconError as ComponentType,
    "notifications:IconWarning": d45.IconWarning as ComponentType,
    "notifications:IconSuccess": d45.IconSuccess as ComponentType,
    "notifications:ProgressNotification": d45.ProgressNotification as ComponentType,
    "notifications:ImageNotification": d45.ImageNotification as ComponentType,
    "notifications:AvatarNotification": d45.AvatarNotification as ComponentType,
    "page-headers:PageHeaderExample": d46.PageHeaderExample as ComponentType,
    "page-headers:Simple": d46.Simple as ComponentType,
    "page-headers:Avatar": d46.Avatar as ComponentType,
    "page-headers:BannerSimple": d46.BannerSimple as ComponentType,
    "page-headers:BannerAvatar": d46.BannerAvatar as ComponentType,
    "page-headers:BannerSimpleCentered": d46.BannerSimpleCentered as ComponentType,
    "page-headers:BannerAvatarCentered": d46.BannerAvatarCentered as ComponentType,
    "pagination:PaginationExample": d47.PaginationExample as ComponentType,
    "pagination:PageDefault": d47.PageDefault as ComponentType,
    "pagination:PageMinimalCenter": d47.PageMinimalCenter as ComponentType,
    "pagination:CardDefault": d47.CardDefault as ComponentType,
    "pagination:CardMinimalRightAligned": d47.CardMinimalRightAligned as ComponentType,
    "pagination:CardMinimalCenterAligned": d47.CardMinimalCenterAligned as ComponentType,
    "pagination:CardMinimalLeftAligned": d47.CardMinimalLeftAligned as ComponentType,
    "pagination:ButtonGroupRightAligned": d47.ButtonGroupRightAligned as ComponentType,
    "pagination:ButtonGroupCenterAligned": d47.ButtonGroupCenterAligned as ComponentType,
    "pagination:ButtonGroupLeftAligned": d47.ButtonGroupLeftAligned as ComponentType,
    "pagination:CardAdvanced": d47.CardAdvanced as ComponentType,
    "pagination:CardAdvancedCenter": d47.CardAdvancedCenter as ComponentType,
    "pagination:PaginationDot": d47.PaginationDot as ComponentType,
    "pagination:Cursor": d47.Cursor as ComponentType,
    "pagination:PaginationLine": d47.PaginationLine as ComponentType,
    "progress-steps:ProgressStepsExample": d48.ProgressStepsExample as ComponentType,
    "progress-steps:IconCentered": d48.IconCentered as ComponentType,
    "progress-steps:IconCenteredWithNumber": d48.IconCenteredWithNumber as ComponentType,
    "progress-steps:FeaturedIconCentered": d48.FeaturedIconCentered as ComponentType,
    "progress-steps:IconWithText": d48.IconWithText as ComponentType,
    "progress-steps:IconWithNumber": d48.IconWithNumber as ComponentType,
    "progress-steps:FeaturedIconWithText": d48.FeaturedIconWithText as ComponentType,
    "progress-steps:MinimalIcons": d48.MinimalIcons as ComponentType,
    "progress-steps:MinimalIconsConnected": d48.MinimalIconsConnected as ComponentType,
    "progress-steps:Interactive": d48.Interactive as ComponentType,
    "progress-steps:WithStepContent": d48.WithStepContent as ComponentType,
    "progress-steps:TextWithLine": d48.TextWithLine as ComponentType,
    "resizable:ResizableExample": d49.ResizableExample as ComponentType,
    "resizable:Vertical": d49.Vertical as ComponentType,
    "resizable:CollapsibleSidebar": d49.CollapsibleSidebar as ComponentType,
    "resizable:Nested": d49.Nested as ComponentType,
    "scroll-area:ScrollAreaExample": d50.ScrollAreaExample as ComponentType,
    "scroll-area:Horizontal": d50.Horizontal as ComponentType,
    "scroll-area:BothAxes": d50.BothAxes as ComponentType,
    "scroll-area:FadeEdges": d50.FadeEdges as ComponentType,
    "section-footers:SectionFooterExample": d51.SectionFooterExample as ComponentType,
    "section-footers:SectionFooterButtonGroup": d51.SectionFooterButtonGroup as ComponentType,
    "section-footers:SectionFooter": d51.SectionFooter as ComponentType,
    "section-footers:SectionFooterCardButtonGroup": d51.SectionFooterCardButtonGroup as ComponentType,
    "section-footers:SectionFooterCard": d51.SectionFooterCard as ComponentType,
    "section-headers:SectionHeaderExample": d52.SectionHeaderExample as ComponentType,
    "section-headers:SectionHeaderButtons": d52.SectionHeaderButtons as ComponentType,
    "section-headers:SectionHeaderSearchInput": d52.SectionHeaderSearchInput as ComponentType,
    "section-headers:SectionHeaderButtonGroup": d52.SectionHeaderButtonGroup as ComponentType,
    "section-headers:SectionHeaderButtonsWithTabs": d52.SectionHeaderButtonsWithTabs as ComponentType,
    "section-headers:SectionHeaderSearchInputWithTabs": d52.SectionHeaderSearchInputWithTabs as ComponentType,
    "section-headers:SectionHeaderButtonGroupsWithTabs": d52.SectionHeaderButtonGroupsWithTabs as ComponentType,
    "slideout-menus:DrawerExample": d53.DrawerExample as ComponentType,
    "slideout-menus:PlaceholderMenu": d53.PlaceholderMenu as ComponentType,
    "slideout-menus:UserProfileMenu": d53.UserProfileMenu as ComponentType,
    "slideout-menus:MessagesMenu": d53.MessagesMenu as ComponentType,
    "slideout-menus:MessageChatMenu": d53.MessageChatMenu as ComponentType,
    "slideout-menus:PaymentMethodMenu": d53.PaymentMethodMenu as ComponentType,
    "slideout-menus:PaymentDetailsMenu": d53.PaymentDetailsMenu as ComponentType,
    "slideout-menus:PlanMenu": d53.PlanMenu as ComponentType,
    "slideout-menus:TeamMembersMenu": d53.TeamMembersMenu as ComponentType,
    "slideout-menus:FiltersMenu": d53.FiltersMenu as ComponentType,
    "slideout-menus:FiltersAdvancedEmptyStateMenu": d53.FiltersAdvancedEmptyStateMenu as ComponentType,
    "slideout-menus:FiltersAdvancedActiveMenu": d53.FiltersAdvancedActiveMenu as ComponentType,
    "slideout-menus:FileUploadMenu": d53.FileUploadMenu as ComponentType,
    "slideout-menus:LabelsMenu": d53.LabelsMenu as ComponentType,
    "slideout-menus:ProjectDetailsMenu": d53.ProjectDetailsMenu as ComponentType,
    "slideout-menus:NotificationSettingsCheckboxMenu": d53.NotificationSettingsCheckboxMenu as ComponentType,
    "slideout-menus:NotificationSettingsButtonMenu": d53.NotificationSettingsButtonMenu as ComponentType,
    "slideout-menus:NotificationsMenu": d53.NotificationsMenu as ComponentType,
    "slideout-menus:OrderSummaryMenu": d53.OrderSummaryMenu as ComponentType,
    "slideout-menus:CalendarEventMenu": d53.CalendarEventMenu as ComponentType,
    "slideout-menus:UserSettingsMenu": d53.UserSettingsMenu as ComponentType,
    "slideout-menus:AIAssistantMenu": d53.AIAssistantMenu as ComponentType,
    "slideout-menus:AIAssistantMessageMenu": d53.AIAssistantMessageMenu as ComponentType,
    "slideout-menus:ShareProjectMenu": d53.ShareProjectMenu as ComponentType,
    "slideout-menus:CreateEventMenu": d53.CreateEventMenu as ComponentType,
    "slideout-menus:IntegrationMenu": d53.IntegrationMenu as ComponentType,
    "sortable-list:SortableListExample": d54.SortableListExample as ComponentType,
    "sortable-list:SettingsSections": d54.SettingsSections as ComponentType,
    "sortable-list:CardsVariant": d54.CardsVariant as ComponentType,
    "stepper:CheckoutExample": d55.CheckoutExample as ComponentType,
    "stepper:VerticalLayout": d55.VerticalLayout as ComponentType,
    "stepper:NonLinear": d55.NonLinear as ComponentType,
    "table:TableExample": d56.TableExample as ComponentType,
    "table:TableSmallSizeExample": d56.TableSmallSizeExample as ComponentType,
    "table:DividerLine01": d56.DividerLine01 as ComponentType,
    "table:AlternatingFills01": d56.AlternatingFills01 as ComponentType,
    "table:DividerLine02": d56.DividerLine02 as ComponentType,
    "table:AlternatingFills02": d56.AlternatingFills02 as ComponentType,
    "table:DividerLine03": d56.DividerLine03 as ComponentType,
    "table:AlternatingFills03": d56.AlternatingFills03 as ComponentType,
    "table:DividerLine04": d56.DividerLine04 as ComponentType,
    "table:AlternatingFills04": d56.AlternatingFills04 as ComponentType,
    "table:StaticUsage": d56.StaticUsage as ComponentType,
    "table:VisuallyHiddenColumnLabel": d56.VisuallyHiddenColumnLabel as ComponentType,
    "table:NoVendorsFound": d56.NoVendorsFound as ComponentType,
    "table:SomethingWentWrong": d56.SomethingWentWrong as ComponentType,
    "table:NoUsersFound": d56.NoUsersFound as ComponentType,
    "table:AddFirstIntegration": d56.AddFirstIntegration as ComponentType,
    "table:InviteFirstUser": d56.InviteFirstUser as ComponentType,
    "table:OfflineState": d56.OfflineState as ComponentType,
    "tabs:TabsExample": d57.TabsExample as ComponentType,
    "tabs:ButtonBrandHorizontal": d57.ButtonBrandHorizontal as ComponentType,
    "tabs:ButtonGrayHorizontal": d57.ButtonGrayHorizontal as ComponentType,
    "tabs:ButtonBorderHorizontal": d57.ButtonBorderHorizontal as ComponentType,
    "tabs:ButtonMinimalHorizontal": d57.ButtonMinimalHorizontal as ComponentType,
    "tabs:Underline": d57.Underline as ComponentType,
    "tabs:ButtonBrandVertical": d57.ButtonBrandVertical as ComponentType,
    "tabs:ButtonGrayVertical": d57.ButtonGrayVertical as ComponentType,
    "tabs:ButtonBorderVertical": d57.ButtonBorderVertical as ComponentType,
    "tabs:ButtonMinimalVertical": d57.ButtonMinimalVertical as ComponentType,
    "tabs:Line": d57.Line as ComponentType,
    "timeline:OrderTracking": d58.OrderTracking as ComponentType,
    "timeline:ReleaseHistory": d58.ReleaseHistory as ComponentType,
    "timeline:Horizontal": d58.Horizontal as ComponentType,
    "timeline:PlainDots": d58.PlainDots as ComponentType,
    "tree-view:TreeViewExample": d59.TreeViewExample as ComponentType,
    "tree-view:SimpleSm": d59.SimpleSm as ComponentType,
    "tree-view:SimpleMd": d59.SimpleMd as ComponentType,
    "tree-view:AdvancedSm": d59.AdvancedSm as ComponentType,
    "tree-view:AdvancedMd": d59.AdvancedMd as ComponentType,
    "avatar:AvatarExample": d60.AvatarExample as ComponentType,
    "avatar:Avatar": d60.Avatar as ComponentType,
    "avatar:BorderExample": d60.BorderExample as ComponentType,
    "avatar:StatusIndicatorExample": d60.StatusIndicatorExample as ComponentType,
    "avatar:CompanyLogoExample": d60.CompanyLogoExample as ComponentType,
    "avatar:VerifiedBadgeExample": d60.VerifiedBadgeExample as ComponentType,
    "avatar:PlaceholderExample": d60.PlaceholderExample as ComponentType,
    "avatar:InitialsExample": d60.InitialsExample as ComponentType,
    "avatar:LabelGroupExample": d60.LabelGroupExample as ComponentType,
    "avatar:GroupExample": d60.GroupExample as ComponentType,
    "avatar:ProfilePhoto": d60.ProfilePhoto as ComponentType,
    "avatar:ProfilePhotoPlaceholderExample": d60.ProfilePhotoPlaceholderExample as ComponentType,
    "avatar:ProfilePhotoInitialsExample": d60.ProfilePhotoInitialsExample as ComponentType,
    "badge-groups:BadgeGroupExample": d61.BadgeGroupExample as ComponentType,
    "badge-groups:PillColorLeadingGray": d61.PillColorLeadingGray as ComponentType,
    "badge-groups:PillColorLeadingBrand": d61.PillColorLeadingBrand as ComponentType,
    "badge-groups:PillColorLeadingError": d61.PillColorLeadingError as ComponentType,
    "badge-groups:PillColorLeadingWarning": d61.PillColorLeadingWarning as ComponentType,
    "badge-groups:PillColorLeadingSuccess": d61.PillColorLeadingSuccess as ComponentType,
    "badge-groups:PillColorTrailingGray": d61.PillColorTrailingGray as ComponentType,
    "badge-groups:PillColorTrailingBrand": d61.PillColorTrailingBrand as ComponentType,
    "badge-groups:PillColorTrailingError": d61.PillColorTrailingError as ComponentType,
    "badge-groups:PillColorTrailingWarning": d61.PillColorTrailingWarning as ComponentType,
    "badge-groups:PillColorTrailingSuccess": d61.PillColorTrailingSuccess as ComponentType,
    "badge-groups:ModernLeadingGray": d61.ModernLeadingGray as ComponentType,
    "badge-groups:ModernLeadingBrand": d61.ModernLeadingBrand as ComponentType,
    "badge-groups:ModernLeadingError": d61.ModernLeadingError as ComponentType,
    "badge-groups:ModernLeadingWarning": d61.ModernLeadingWarning as ComponentType,
    "badge-groups:ModernLeadingSuccess": d61.ModernLeadingSuccess as ComponentType,
    "badge-groups:ModernTrailingGray": d61.ModernTrailingGray as ComponentType,
    "badge-groups:ModernTrailingBrand": d61.ModernTrailingBrand as ComponentType,
    "badge-groups:ModernTrailingError": d61.ModernTrailingError as ComponentType,
    "badge-groups:ModernTrailingWarning": d61.ModernTrailingWarning as ComponentType,
    "badge-groups:ModernTrailingSuccess": d61.ModernTrailingSuccess as ComponentType,
    "badges:BadgeExample": d62.BadgeExample as ComponentType,
    "badges:PillColor": d62.PillColor as ComponentType,
    "badges:Color": d62.Color as ComponentType,
    "badges:Modern": d62.Modern as ComponentType,
    "badges:WithDot": d62.WithDot as ComponentType,
    "badges:WithDotBadgeColor": d62.WithDotBadgeColor as ComponentType,
    "badges:WithDotBadgeModern": d62.WithDotBadgeModern as ComponentType,
    "badges:WithFlag": d62.WithFlag as ComponentType,
    "badges:WithFlagBadgeColor": d62.WithFlagBadgeColor as ComponentType,
    "badges:WithFlagBadgeModern": d62.WithFlagBadgeModern as ComponentType,
    "badges:WithAvatar": d62.WithAvatar as ComponentType,
    "badges:WithAvatarBadgeColor": d62.WithAvatarBadgeColor as ComponentType,
    "badges:WithAvatarBadgeModern": d62.WithAvatarBadgeModern as ComponentType,
    "badges:WithCloseX": d62.WithCloseX as ComponentType,
    "badges:WithCloseXBadgeColor": d62.WithCloseXBadgeColor as ComponentType,
    "badges:WithCloseXBadgeModern": d62.WithCloseXBadgeModern as ComponentType,
    "badges:WithIconLeading": d62.WithIconLeading as ComponentType,
    "badges:ColorWithIconLeading": d62.ColorWithIconLeading as ComponentType,
    "badges:ModernWithIconLeading": d62.ModernWithIconLeading as ComponentType,
    "badges:WithIconTrailing": d62.WithIconTrailing as ComponentType,
    "badges:ColorWithIconTrailing": d62.ColorWithIconTrailing as ComponentType,
    "badges:ModernWithIconTrailing": d62.ModernWithIconTrailing as ComponentType,
    "badges:WithIconOnly": d62.WithIconOnly as ComponentType,
    "badges:ColorWithIconOnly": d62.ColorWithIconOnly as ComponentType,
    "badges:ModernWithIconOnly": d62.ModernWithIconOnly as ComponentType,
    "button-group:ButtonGroupExample": d63.ButtonGroupExample as ComponentType,
    "button-group:LeadingIcon": d63.LeadingIcon as ComponentType,
    "button-group:WithDot": d63.WithDot as ComponentType,
    "button-group:Disabled": d63.Disabled as ComponentType,
    "button-group:DisabledIndividualItem": d63.DisabledIndividualItem as ComponentType,
    "button-group:Selection": d63.Selection as ComponentType,
    "button-group:MultipleSelection": d63.MultipleSelection as ComponentType,
    "app-store-buttons:MobileAppStoreButtonsExample": d64.MobileAppStoreButtonsExample as ComponentType,
    "app-store-buttons:GooglePlayButtons": d64.GooglePlayButtons as ComponentType,
    "app-store-buttons:AppStoreButtons": d64.AppStoreButtons as ComponentType,
    "app-store-buttons:GalaxyStoreButtons": d64.GalaxyStoreButtons as ComponentType,
    "app-store-buttons:AppGalleryButtons": d64.AppGalleryButtons as ComponentType,
    "app-store-buttons:GooglePlayOutlineButtons": d64.GooglePlayOutlineButtons as ComponentType,
    "app-store-buttons:AppStoreOutlineButtons": d64.AppStoreOutlineButtons as ComponentType,
    "app-store-buttons:GalaxyStoreOutlineButtons": d64.GalaxyStoreOutlineButtons as ComponentType,
    "app-store-buttons:AppGalleryOutlineButtons": d64.AppGalleryOutlineButtons as ComponentType,
    "button-utility:UtilityButtonsExample": d65.UtilityButtonsExample as ComponentType,
    "button-utility:Secondary": d65.Secondary as ComponentType,
    "button-utility:Tertiary": d65.Tertiary as ComponentType,
    "button-utility:Sizes": d65.Sizes as ComponentType,
    "button-utility:Disabled": d65.Disabled as ComponentType,
    "button-utility:CloseX": d65.CloseX as ComponentType,
    "button-utility:CloseXDark": d65.CloseXDark as ComponentType,
    "buttons:ButtonExample": d66.ButtonExample as ComponentType,
    "buttons:PrimaryButtons": d66.PrimaryButtons as ComponentType,
    "buttons:SecondaryButtons": d66.SecondaryButtons as ComponentType,
    "buttons:TertiaryButtons": d66.TertiaryButtons as ComponentType,
    "buttons:LinkColorButtonsExample": d66.LinkColorButtonsExample as ComponentType,
    "buttons:LinkGrayButtons": d66.LinkGrayButtons as ComponentType,
    "buttons:IconLeadingButtonsExample": d66.IconLeadingButtonsExample as ComponentType,
    "buttons:IconTrailingButtonsExample": d66.IconTrailingButtonsExample as ComponentType,
    "buttons:IconOnlyButtonsExample": d66.IconOnlyButtonsExample as ComponentType,
    "buttons:LoadingButtonsExample": d66.LoadingButtonsExample as ComponentType,
    "buttons:DisabledButtonsExample": d66.DisabledButtonsExample as ComponentType,
    "buttons:PrimaryButtonsDestructiveExample": d66.PrimaryButtonsDestructiveExample as ComponentType,
    "buttons:SecondaryButtonsDestructive": d66.SecondaryButtonsDestructive as ComponentType,
    "buttons:TertiaryButtonsDestructive": d66.TertiaryButtonsDestructive as ComponentType,
    "social-buttons:SocialButtonsExample": d67.SocialButtonsExample as ComponentType,
    "social-buttons:GoogleSocialButtons": d67.GoogleSocialButtons as ComponentType,
    "social-buttons:FacebookSocialButtons": d67.FacebookSocialButtons as ComponentType,
    "social-buttons:AppleSocialButtons": d67.AppleSocialButtons as ComponentType,
    "social-buttons:TwitterSocialButtons": d67.TwitterSocialButtons as ComponentType,
    "social-buttons:FigmaSocialButtons": d67.FigmaSocialButtons as ComponentType,
    "social-buttons:DribbleSocialButtons": d67.DribbleSocialButtons as ComponentType,
    "social-buttons:BrandSocialButtonsGroup": d67.BrandSocialButtonsGroup as ComponentType,
    "social-buttons:IconsBrandSocialButtonsGroup": d67.IconsBrandSocialButtonsGroup as ComponentType,
    "social-buttons:ColorSocialButtonsGroup": d67.ColorSocialButtonsGroup as ComponentType,
    "social-buttons:IconsColorSocialButtonsGroup": d67.IconsColorSocialButtonsGroup as ComponentType,
    "social-buttons:GraySocialButtonsGroup": d67.GraySocialButtonsGroup as ComponentType,
    "checkbox:CheckboxExample": d68.CheckboxExample as ComponentType,
    "checkbox:Base": d68.Base as ComponentType,
    "checkbox:WithLabel": d68.WithLabel as ComponentType,
    "checkbox:WithLabelAndHint": d68.WithLabelAndHint as ComponentType,
    "checkbox:Disabled": d68.Disabled as ComponentType,
    "checkbox:Sizes": d68.Sizes as ComponentType,
    "context-menus:ContextMenuExample": d69.ContextMenuExample as ComponentType,
    "context-menus:Simple": d69.Simple as ComponentType,
    "context-menus:Advanced": d69.Advanced as ComponentType,
    "dropdown:DropdownExample": d70.DropdownExample as ComponentType,
    "dropdown:ButtonSimple": d70.ButtonSimple as ComponentType,
    "dropdown:ButtonAdvanced": d70.ButtonAdvanced as ComponentType,
    "dropdown:ButtonLink": d70.ButtonLink as ComponentType,
    "dropdown:IconSimple": d70.IconSimple as ComponentType,
    "dropdown:IconAdvanced": d70.IconAdvanced as ComponentType,
    "dropdown:SearchSimple": d70.SearchSimple as ComponentType,
    "dropdown:SearchAdvanced": d70.SearchAdvanced as ComponentType,
    "dropdown:Integrations": d70.Integrations as ComponentType,
    "dropdown:AccountButton": d70.AccountButton as ComponentType,
    "dropdown:Avatar": d70.Avatar as ComponentType,
    "dropdown:AccountCardXs": d70.AccountCardXs as ComponentType,
    "dropdown:AccountCardSm": d70.AccountCardSm as ComponentType,
    "dropdown:AccountCardMd": d70.AccountCardMd as ComponentType,
    "dropdown:AccountBreadcrumb": d70.AccountBreadcrumb as ComponentType,
    "hover-card:HoverCardExample": d71.HoverCardExample as ComponentType,
    "hover-card:WithInteractiveContent": d71.WithInteractiveContent as ComponentType,
    "hover-card:Placements": d71.Placements as ComponentType,
    "hover-card:CustomDelays": d71.CustomDelays as ComponentType,
    "inputs:InputExample": d72.InputExample as ComponentType,
    "inputs:Default": d72.Default as ComponentType,
    "inputs:Disabled": d72.Disabled as ComponentType,
    "inputs:Invalid": d72.Invalid as ComponentType,
    "inputs:Sizes": d72.Sizes as ComponentType,
    "inputs:LeadingIcon": d72.LeadingIcon as ComponentType,
    "inputs:LeadingDropdown": d72.LeadingDropdown as ComponentType,
    "inputs:TrailingDropdown": d72.TrailingDropdown as ComponentType,
    "inputs:LeadingText": d72.LeadingText as ComponentType,
    "inputs:PaymentInput": d72.PaymentInput as ComponentType,
    "inputs:TrailingButton": d72.TrailingButton as ComponentType,
    "inputs:FileUpload": d72.FileUpload as ComponentType,
    "inputs:PasswordInput": d72.PasswordInput as ComponentType,
    "inputs:DateInput": d72.DateInput as ComponentType,
    "inputs:NumberInputHorizontal": d72.NumberInputHorizontal as ComponentType,
    "inputs:NumberInputVertical": d72.NumberInputVertical as ComponentType,
    "inputs:TagInput": d72.TagInput as ComponentType,
    "inputs:TagInputOuter": d72.TagInputOuter as ComponentType,
    "pin-input:VerificationCodeInputExample": d73.VerificationCodeInputExample as ComponentType,
    "pin-input:FourDigits": d73.FourDigits as ComponentType,
    "pin-input:WithSeparator": d73.WithSeparator as ComponentType,
    "pin-input:InputOTP": d73.InputOTP as ComponentType,
    "pin-input:Disabled": d73.Disabled as ComponentType,
    "pin-input:Sizes": d73.Sizes as ComponentType,
    "menubar:MenubarExample": d74.MenubarExample as ComponentType,
    "menubar:WithDisabledItems": d74.WithDisabledItems as ComponentType,
    "menubar:Minimal": d74.Minimal as ComponentType,
    "number-input:NumberInputExample": d75.NumberInputExample as ComponentType,
    "number-input:FormatOptions": d75.FormatOptions as ComponentType,
    "number-input:InlineButtons": d75.InlineButtons as ComponentType,
    "number-input:Sizes": d75.Sizes as ComponentType,
    "number-input:MinMaxStep": d75.MinMaxStep as ComponentType,
    "number-input:States": d75.States as ComponentType,
    "popover:PopoverExample": d76.PopoverExample as ComponentType,
    "popover:Placements": d76.Placements as ComponentType,
    "popover:WithIconTrigger": d76.WithIconTrigger as ComponentType,
    "progress-indicators:ProgressIndicatorExample": d77.ProgressIndicatorExample as ComponentType,
    "progress-indicators:Default": d77.Default as ComponentType,
    "progress-indicators:TextRight": d77.TextRight as ComponentType,
    "progress-indicators:TextBottom": d77.TextBottom as ComponentType,
    "progress-indicators:TextTopFloating": d77.TextTopFloating as ComponentType,
    "progress-indicators:TextBottomFloating": d77.TextBottomFloating as ComponentType,
    "progress-indicators:CircleProgressBar": d77.CircleProgressBar as ComponentType,
    "progress-indicators:CircleProgressBarLabel": d77.CircleProgressBarLabel as ComponentType,
    "progress-indicators:HalfCircleProgressBar": d77.HalfCircleProgressBar as ComponentType,
    "progress-indicators:HalfCircleProgressBarLabel": d77.HalfCircleProgressBarLabel as ComponentType,
    "radio-buttons:RadioButtonExample": d78.RadioButtonExample as ComponentType,
    "radio-buttons:WithLabel": d78.WithLabel as ComponentType,
    "radio-buttons:WithLabelAndHint": d78.WithLabelAndHint as ComponentType,
    "radio-buttons:Disabled": d78.Disabled as ComponentType,
    "radio-buttons:DisabledIndividualOption": d78.DisabledIndividualOption as ComponentType,
    "radio-buttons:Sizes": d78.Sizes as ComponentType,
    "radio-buttons:IconSimple": d78.IconSimple as ComponentType,
    "radio-buttons:IconCard": d78.IconCard as ComponentType,
    "radio-buttons:Avatar": d78.Avatar as ComponentType,
    "radio-buttons:PaymentIcon": d78.PaymentIcon as ComponentType,
    "radio-buttons:RadioButton": d78.RadioButton as ComponentType,
    "radio-buttons:Checkbox": d78.Checkbox as ComponentType,
    "multi-select:MultiSelectExample": d79.MultiSelectExample as ComponentType,
    "multi-select:Default": d79.Default as ComponentType,
    "multi-select:WithLeadingIcon": d79.WithLeadingIcon as ComponentType,
    "multi-select:Disabled": d79.Disabled as ComponentType,
    "multi-select:Sizes": d79.Sizes as ComponentType,
    "select:SelectExample": d80.SelectExample as ComponentType,
    "select:Default": d80.Default as ComponentType,
    "select:Disabled": d80.Disabled as ComponentType,
    "select:Sizes": d80.Sizes as ComponentType,
    "select:IconLeading": d80.IconLeading as ComponentType,
    "select:AvatarLeading": d80.AvatarLeading as ComponentType,
    "select:DotLeading": d80.DotLeading as ComponentType,
    "select:Search": d80.Search as ComponentType,
    "select:Tags": d80.Tags as ComponentType,
    "skeleton:SkeletonExample": d81.SkeletonExample as ComponentType,
    "skeleton:Avatar": d81.Avatar as ComponentType,
    "skeleton:TextBlock": d81.TextBlock as ComponentType,
    "skeleton:CardSkeleton": d81.CardSkeleton as ComponentType,
    "slider:SliderExample": d82.SliderExample as ComponentType,
    "slider:Default": d82.Default as ComponentType,
    "slider:BottomLabel": d82.BottomLabel as ComponentType,
    "slider:TopFloating": d82.TopFloating as ComponentType,
    "slider:SingleThumb": d82.SingleThumb as ComponentType,
    "tag-input:TagInputExample": d83.TagInputExample as ComponentType,
    "tag-input:Controlled": d83.Controlled as ComponentType,
    "tag-input:MaxTagsWithFeedback": d83.MaxTagsWithFeedback as ComponentType,
    "tag-input:WithValidation": d83.WithValidation as ComponentType,
    "tag-input:States": d83.States as ComponentType,
    "tags:TagsExample": d84.TagsExample as ComponentType,
    "tags:SizesExample": d84.SizesExample as ComponentType,
    "tags:CloseXExample": d84.CloseXExample as ComponentType,
    "tags:CountExample": d84.CountExample as ComponentType,
    "tags:CheckboxExample": d84.CheckboxExample as ComponentType,
    "tags:CheckboxCloseXExample": d84.CheckboxCloseXExample as ComponentType,
    "tags:CheckboxCountExample": d84.CheckboxCountExample as ComponentType,
    "text-editor:TextEditorExample": d85.TextEditorExample as ComponentType,
    "text-editor:DefaultSm": d85.DefaultSm as ComponentType,
    "text-editor:DefaultMd": d85.DefaultMd as ComponentType,
    "text-editor:FloatingToolbarSm": d85.FloatingToolbarSm as ComponentType,
    "text-editor:FloatingToolbarMd": d85.FloatingToolbarMd as ComponentType,
    "text-editor:WithTooltip": d85.WithTooltip as ComponentType,
    "textarea:TextareaExample": d86.TextareaExample as ComponentType,
    "textarea:Default": d86.Default as ComponentType,
    "textarea:Disabled": d86.Disabled as ComponentType,
    "textarea:Invalid": d86.Invalid as ComponentType,
    "toggle-chip:ToggleChipExample": d87.ToggleChipExample as ComponentType,
    "toggle-chip:Colors": d87.Colors as ComponentType,
    "toggle-chip:Sizes": d87.Sizes as ComponentType,
    "toggle-chip:FilterGroup": d87.FilterGroup as ComponentType,
    "toggle-chip:Disabled": d87.Disabled as ComponentType,
    "toggle:ToggleExample": d88.ToggleExample as ComponentType,
    "toggle:Base": d88.Base as ComponentType,
    "toggle:WithLabel": d88.WithLabel as ComponentType,
    "toggle:WithLabelAndHint": d88.WithLabelAndHint as ComponentType,
    "toggle:Disabled": d88.Disabled as ComponentType,
    "toggle:Sizes": d88.Sizes as ComponentType,
    "toggle:Slim": d88.Slim as ComponentType,
    "toggle:SlimWithLabelAndHint": d88.SlimWithLabelAndHint as ComponentType,
    "tooltip:TooltipExample": d89.TooltipExample as ComponentType,
    "tooltip:DefaultExample": d89.DefaultExample as ComponentType,
    "tooltip:WithArrowExample": d89.WithArrowExample as ComponentType,
    "tooltip:WithSupportingTextExample": d89.WithSupportingTextExample as ComponentType,
    "tooltip:PlacementsExample": d89.PlacementsExample as ComponentType,
    "video-player:VideoPlayerExample": d90.VideoPlayerExample as ComponentType,
    "video-player:VideoPlayerSm": d90.VideoPlayerSm as ComponentType,
    "video-player:VideoPlayerMd": d90.VideoPlayerMd as ComponentType,
    "video-player:VideoPlayerLg": d90.VideoPlayerLg as ComponentType,
    "featured-icon:FeaturedIconExample": d91.FeaturedIconExample as ComponentType,
    "featured-icon:Light": d91.Light as ComponentType,
    "featured-icon:Gradient": d91.Gradient as ComponentType,
    "featured-icon:Dark": d91.Dark as ComponentType,
    "featured-icon:Outline": d91.Outline as ComponentType,
    "featured-icon:Modern": d91.Modern as ComponentType,
    "featured-icon:ModernNeue": d91.ModernNeue as ComponentType,
    "rating:RatingBadgeExample": d92.RatingBadgeExample as ComponentType,
    "rating:RatingStarsExample": d92.RatingStarsExample as ComponentType,
    "typography:ArticleExample": d93.ArticleExample as ComponentType,
    "typography:Headings": d93.Headings as ComponentType,
    "typography:Images": d93.Images as ComponentType,
    "typography:QuoteDefault": d93.QuoteDefault as ComponentType,
    "typography:QuoteWithAvatar": d93.QuoteWithAvatar as ComponentType,
    "typography:QuoteCentered": d93.QuoteCentered as ComponentType,
    "typography:QuoteMinimal": d93.QuoteMinimal as ComponentType,
    "typography:InlineCode": d93.InlineCode as ComponentType,
    "typography:FeatureText": d93.FeatureText as ComponentType,
    "404-pages:Page404Example": d94.Page404Example as ComponentType,
    "about-pages:AboutPageExample": d95.AboutPageExample as ComponentType,
    "blog-pages:BlogExample": d96.BlogExample as ComponentType,
    "blog-post-pages:BlogPostExample": d97.BlogPostExample as ComponentType,
    "contact-pages:ContactPageExample": d98.ContactPageExample as ComponentType,
    "faq-pages:FAQPageExample": d99.FAQPageExample as ComponentType,
    "landing-pages:LandingPageExample": d100.LandingPageExample as ComponentType,
    "legal-pages:LegalPageExample": d101.LegalPageExample as ComponentType,
    "pricing-pages:PricingPageExample": d102.PricingPageExample as ComponentType,
    "team-pages:TeamPageExample": d103.TeamPageExample as ComponentType,
    "banners:BannerExample": d104.BannerExample as ComponentType,
    "blog-sections:BlogSectionExample": d105.BlogSectionExample as ComponentType,
    "careers-sections:CareersSectionExample": d106.CareersSectionExample as ComponentType,
    "contact-sections:ContactSectionExample": d107.ContactSectionExample as ComponentType,
    "content-rich-text-sections:ContentRichTextSectionExample": d108.ContentRichTextSectionExample as ComponentType,
    "cta-sections:CTASectionExample": d109.CTASectionExample as ComponentType,
    "faq-sections:FAQSectionExample": d110.FAQSectionExample as ComponentType,
    "features-sections:FeaturesSectionExample": d111.FeaturesSectionExample as ComponentType,
    "footers:FooterExample": d112.FooterExample as ComponentType,
    "header-navigations:HeaderNavigationExample": d113.HeaderNavigationExample as ComponentType,
    "header-sections:HeaderSectionExample": d114.HeaderSectionExample as ComponentType,
    "hero-header-sections:HeroHeaderSectionExample": d115.HeroHeaderSectionExample as ComponentType,
    "metrics-sections:MetricsSectionExample": d116.MetricsSectionExample as ComponentType,
    "newsletter-cta-sections:NewsletterCTASectionExample": d117.NewsletterCTASectionExample as ComponentType,
    "pricing-sections:PricingSectionExample": d118.PricingSectionExample as ComponentType,
    "social-proof-sections:SocialProofSectionExample": d119.SocialProofSectionExample as ComponentType,
    "team-sections:TeamSectionExample": d120.TeamSectionExample as ComponentType,
    "testimonial-sections:TestimonialsSectionExample": d121.TestimonialsSectionExample as ComponentType,
    "credit-card:CreditCardExample": d122.CreditCardExample as ComponentType,
    "credit-card:CustomizationExample": d122.CustomizationExample as ComponentType,
    "credit-card:SizesExample": d122.SizesExample as ComponentType,
    "credit-card:Transparent": d122.Transparent as ComponentType,
    "credit-card:TransparentGradient": d122.TransparentGradient as ComponentType,
    "credit-card:BrandDark": d122.BrandDark as ComponentType,
    "credit-card:BrandLight": d122.BrandLight as ComponentType,
    "credit-card:GrayDark": d122.GrayDark as ComponentType,
    "credit-card:GrayLight": d122.GrayLight as ComponentType,
    "credit-card:TransparentStrip": d122.TransparentStrip as ComponentType,
    "credit-card:GrayStrip": d122.GrayStrip as ComponentType,
    "credit-card:GradientStrip": d122.GradientStrip as ComponentType,
    "credit-card:SalmonStrip": d122.SalmonStrip as ComponentType,
    "credit-card:GrayStripVertical": d122.GrayStripVertical as ComponentType,
    "credit-card:GradientStripVertical": d122.GradientStripVertical as ComponentType,
    "credit-card:SalmonStripVertical": d122.SalmonStripVertical as ComponentType,
    "illustrations:IllustrationExample": d123.IllustrationExample as ComponentType,
    "illustrations:BoxSm": d123.BoxSm as ComponentType,
    "illustrations:BoxMd": d123.BoxMd as ComponentType,
    "illustrations:BoxLg": d123.BoxLg as ComponentType,
    "illustrations:CloudSm": d123.CloudSm as ComponentType,
    "illustrations:CloudMd": d123.CloudMd as ComponentType,
    "illustrations:CloudLg": d123.CloudLg as ComponentType,
    "illustrations:CreditCardSm": d123.CreditCardSm as ComponentType,
    "illustrations:CreditCardMd": d123.CreditCardMd as ComponentType,
    "illustrations:CreditCardLg": d123.CreditCardLg as ComponentType,
    "illustrations:DocumentsSm": d123.DocumentsSm as ComponentType,
    "illustrations:DocumentsMd": d123.DocumentsMd as ComponentType,
    "illustrations:DocumentsLg": d123.DocumentsLg as ComponentType,
    "qr-code:QRCodeExample": d124.QRCodeExample as ComponentType,
    "qr-code:DefaultExample": d124.DefaultExample as ComponentType,
    "qr-code:LargeExample": d124.LargeExample as ComponentType,
    "qr-code:WithGradientScanExample": d124.WithGradientScanExample as ComponentType,
    "qr-code:WithCustomOptionsExample": d124.WithCustomOptionsExample as ComponentType,
};
