// GENERATED FILE — do not edit by hand. Run `pnpm gen:demos`.
import type { ComponentType } from "react";
import * as d0 from "@properui/ui/components/app-examples/404-sections/404-sections.demo";
import * as d1 from "@properui/ui/components/app-examples/dashboards-02/dashboards-02.demo";
import * as d2 from "@properui/ui/components/app-examples/dashboards/dashboards.demo";
import * as d3 from "@properui/ui/components/app-examples/email-templates/email-templates.demo";
import * as d4 from "@properui/ui/components/app-examples/forgot-password-pages/forgot-password-pages.demo";
import * as d5 from "@properui/ui/components/app-examples/informational-pages-02/informational-pages-02.demo";
import * as d6 from "@properui/ui/components/app-examples/informational-pages/informational-pages.demo";
import * as d7 from "@properui/ui/components/app-examples/log-in-pages/log-in-pages.demo";
import * as d8 from "@properui/ui/components/app-examples/settings-pages-02/settings-pages-02.demo";
import * as d9 from "@properui/ui/components/app-examples/settings-pages/settings-pages.demo";
import * as d10 from "@properui/ui/components/app-examples/sign-up-pages/sign-up-pages.demo";
import * as d11 from "@properui/ui/components/app-examples/verification-pages/verification-pages.demo";
import * as d12 from "@properui/ui/components/application/activity-feed/activity-feed.demo";
import * as d13 from "@properui/ui/components/application/ai-elements/ai-elements.demo";
import * as d14 from "@properui/ui/components/application/alerts/alerts.demo";
import * as d15 from "@properui/ui/components/application/app-navigation/header-navigation.demo";
import * as d16 from "@properui/ui/components/application/app-navigation/sidebar-navigation.demo";
import * as d17 from "@properui/ui/components/application/breadcrumbs/breadcrumbs.demo";
import * as d18 from "@properui/ui/components/application/callout/callout.demo";
import * as d19 from "@properui/ui/components/application/card-headers/card-headers.demo";
import * as d20 from "@properui/ui/components/application/carousel/carousel.demo";
import * as d21 from "@properui/ui/components/application/charts/activity-gauges.demo";
import * as d22 from "@properui/ui/components/application/charts/area-charts.demo";
import * as d23 from "@properui/ui/components/application/charts/combined-charts.demo";
import * as d24 from "@properui/ui/components/application/charts/line-bar-charts.demo";
import * as d25 from "@properui/ui/components/application/charts/pie-charts.demo";
import * as d26 from "@properui/ui/components/application/charts/radar-charts.demo";
import * as d27 from "@properui/ui/components/application/charts/scatter-bubble-charts.demo";
import * as d28 from "@properui/ui/components/application/charts/sparklines.demo";
import * as d29 from "@properui/ui/components/application/code-editor/code-editor.demo";
import * as d30 from "@properui/ui/components/application/code-snippet/code-snippet.demo";
import * as d31 from "@properui/ui/components/application/color-picker/color-picker.demo";
import * as d32 from "@properui/ui/components/application/command-menu/command-menu.demo";
import * as d33 from "@properui/ui/components/application/confirm-dialog/confirm-dialog.demo";
import * as d34 from "@properui/ui/components/application/content-divider/content-divider.demo";
import * as d35 from "@properui/ui/components/application/data-table/data-table.demo";
import * as d36 from "@properui/ui/components/application/date-picker/calendar.demo";
import * as d37 from "@properui/ui/components/application/date-picker/date-pickers.demo";
import * as d38 from "@properui/ui/components/application/description-list/description-list.demo";
import * as d39 from "@properui/ui/components/application/empty-state/empty-state.demo";
import * as d40 from "@properui/ui/components/application/file-upload/file-upload.demo";
import * as d41 from "@properui/ui/components/application/filter-bar/filter-bars.demo";
import * as d42 from "@properui/ui/components/application/gantt/gantt.demo";
import * as d43 from "@properui/ui/components/application/gradient-picker/gradient-picker.demo";
import * as d44 from "@properui/ui/components/application/image-picker/image-picker.demo";
import * as d45 from "@properui/ui/components/application/inline-cta/inline-cta.demo";
import * as d46 from "@properui/ui/components/application/kanban/kanban.demo";
import * as d47 from "@properui/ui/components/application/loading-indicator/loading-indicator.demo";
import * as d48 from "@properui/ui/components/application/messaging/messaging.demo";
import * as d49 from "@properui/ui/components/application/metrics/metrics.demo";
import * as d50 from "@properui/ui/components/application/modals/modals.demo";
import * as d51 from "@properui/ui/components/application/notifications/notifications.demo";
import * as d52 from "@properui/ui/components/application/page-headers/page-headers.demo";
import * as d53 from "@properui/ui/components/application/pagination/pagination.demo";
import * as d54 from "@properui/ui/components/application/progress-steps/progress-steps.demo";
import * as d55 from "@properui/ui/components/application/resizable/resizable.demo";
import * as d56 from "@properui/ui/components/application/scroll-area/scroll-area.demo";
import * as d57 from "@properui/ui/components/application/section-footers/section-footers.demo";
import * as d58 from "@properui/ui/components/application/section-headers/section-headers.demo";
import * as d59 from "@properui/ui/components/application/slideout-menus/slideout-menus.demo";
import * as d60 from "@properui/ui/components/application/sortable-list/sortable-list.demo";
import * as d61 from "@properui/ui/components/application/stepper/stepper.demo";
import * as d62 from "@properui/ui/components/application/table/table.demo";
import * as d63 from "@properui/ui/components/application/tabs/tabs.demo";
import * as d64 from "@properui/ui/components/application/timeline/timeline.demo";
import * as d65 from "@properui/ui/components/application/tree-view/tree-view.demo";
import * as d66 from "@properui/ui/components/base/avatar/avatar.demo";
import * as d67 from "@properui/ui/components/base/badges/badge-groups.demo";
import * as d68 from "@properui/ui/components/base/badges/badges.demo";
import * as d69 from "@properui/ui/components/base/button-group/button-group.demo";
import * as d70 from "@properui/ui/components/base/buttons/app-store-buttons.demo";
import * as d71 from "@properui/ui/components/base/buttons/button-utility.demo";
import * as d72 from "@properui/ui/components/base/buttons/buttons.demo";
import * as d73 from "@properui/ui/components/base/buttons/social-buttons.demo";
import * as d74 from "@properui/ui/components/base/checkbox/checkbox.demo";
import * as d75 from "@properui/ui/components/base/dropdown/context-menus.demo";
import * as d76 from "@properui/ui/components/base/dropdown/dropdown.demo";
import * as d77 from "@properui/ui/components/base/hover-card/hover-card.demo";
import * as d78 from "@properui/ui/components/base/input/inputs.demo";
import * as d79 from "@properui/ui/components/base/input/pin-input.demo";
import * as d80 from "@properui/ui/components/base/menubar/menubar.demo";
import * as d81 from "@properui/ui/components/base/number-input/number-input.demo";
import * as d82 from "@properui/ui/components/base/popover/popover.demo";
import * as d83 from "@properui/ui/components/base/progress-indicators/progress-indicators.demo";
import * as d84 from "@properui/ui/components/base/radio-buttons/radio-buttons.demo";
import * as d85 from "@properui/ui/components/base/select/multi-select.demo";
import * as d86 from "@properui/ui/components/base/select/select.demo";
import * as d87 from "@properui/ui/components/base/skeleton/skeleton.demo";
import * as d88 from "@properui/ui/components/base/slider/slider.demo";
import * as d89 from "@properui/ui/components/base/tag-input/tag-input.demo";
import * as d90 from "@properui/ui/components/base/tags/tags.demo";
import * as d91 from "@properui/ui/components/base/text-editor/text-editor.demo";
import * as d92 from "@properui/ui/components/base/textarea/textarea.demo";
import * as d93 from "@properui/ui/components/base/toggle-chip/toggle-chip.demo";
import * as d94 from "@properui/ui/components/base/toggle/toggle.demo";
import * as d95 from "@properui/ui/components/base/tooltip/tooltip.demo";
import * as d96 from "@properui/ui/components/base/video-player/video-player.demo";
import * as d97 from "@properui/ui/components/foundations/featured-icon/featured-icon.demo";
import * as d98 from "@properui/ui/components/foundations/rating/rating.demo";
import * as d99 from "@properui/ui/components/foundations/typography/typography.demo";
import * as d100 from "@properui/ui/components/marketing-examples/404-pages/404-pages.demo";
import * as d101 from "@properui/ui/components/marketing-examples/about-pages/about-pages.demo";
import * as d102 from "@properui/ui/components/marketing-examples/blog-pages/blog-pages.demo";
import * as d103 from "@properui/ui/components/marketing-examples/blog-post-pages/blog-post-pages.demo";
import * as d104 from "@properui/ui/components/marketing-examples/contact-pages/contact-pages.demo";
import * as d105 from "@properui/ui/components/marketing-examples/faq-pages/faq-pages.demo";
import * as d106 from "@properui/ui/components/marketing-examples/landing-pages/landing-pages.demo";
import * as d107 from "@properui/ui/components/marketing-examples/legal-pages/legal-pages.demo";
import * as d108 from "@properui/ui/components/marketing-examples/pricing-pages/pricing-pages.demo";
import * as d109 from "@properui/ui/components/marketing-examples/team-pages/team-pages.demo";
import * as d110 from "@properui/ui/components/marketing/banners/banners.demo";
import * as d111 from "@properui/ui/components/marketing/blog-sections/blog-sections.demo";
import * as d112 from "@properui/ui/components/marketing/careers-sections/careers-sections.demo";
import * as d113 from "@properui/ui/components/marketing/contact-sections/contact-sections.demo";
import * as d114 from "@properui/ui/components/marketing/content-rich-text-sections/content-rich-text-sections.demo";
import * as d115 from "@properui/ui/components/marketing/cta-sections/cta-sections.demo";
import * as d116 from "@properui/ui/components/marketing/faq-sections/faq-sections.demo";
import * as d117 from "@properui/ui/components/marketing/features-sections/features-sections.demo";
import * as d118 from "@properui/ui/components/marketing/footers/footers.demo";
import * as d119 from "@properui/ui/components/marketing/header-navigations/header-navigations.demo";
import * as d120 from "@properui/ui/components/marketing/header-sections/header-sections.demo";
import * as d121 from "@properui/ui/components/marketing/hero-header-sections/hero-header-sections.demo";
import * as d122 from "@properui/ui/components/marketing/metrics-sections/metrics-sections.demo";
import * as d123 from "@properui/ui/components/marketing/newsletter-cta-sections/newsletter-cta-sections.demo";
import * as d124 from "@properui/ui/components/marketing/pricing-sections/pricing-sections.demo";
import * as d125 from "@properui/ui/components/marketing/social-proof-sections/social-proof-sections.demo";
import * as d126 from "@properui/ui/components/marketing/team-sections/team-sections.demo";
import * as d127 from "@properui/ui/components/marketing/testimonial-sections/testimonial-sections.demo";
import * as d128 from "@properui/ui/components/shared-assets/credit-card/credit-card.demo";
import * as d129 from "@properui/ui/components/shared-assets/illustrations/illustrations.demo";
import * as d130 from "@properui/ui/components/shared-assets/qr-code/qr-code.demo";

export const demos: Record<string, ComponentType> = {
    "404-sections:Section404Example": d0.Section404Example as ComponentType,
    "dashboards-02:DashboardWithHeaderNavigationExample": d1.DashboardWithHeaderNavigationExample as ComponentType,
    "dashboards:DashboardWithSidebarNavigationExample": d2.DashboardWithSidebarNavigationExample as ComponentType,
    "email-templates:EmailTemplateExample": d3.EmailTemplateExample as ComponentType,
    "forgot-password-pages:ForgotPasswordPageExample": d4.ForgotPasswordPageExample as ComponentType,
    "informational-pages-02:InformationalPageWithHeaderNavigationExample": d5.InformationalPageWithHeaderNavigationExample as ComponentType,
    "informational-pages:InformationalPageWithSidebarNavigationExample": d6.InformationalPageWithSidebarNavigationExample as ComponentType,
    "log-in-pages:LogInPageExample": d7.LogInPageExample as ComponentType,
    "settings-pages-02:SettingsPageWithHeaderNavigationExample": d8.SettingsPageWithHeaderNavigationExample as ComponentType,
    "settings-pages:SettingsPageWithSidebarNavigationExample": d9.SettingsPageWithSidebarNavigationExample as ComponentType,
    "sign-up-pages:SignUpPageExample": d10.SignUpPageExample as ComponentType,
    "verification-pages:VerificationPageExample": d11.VerificationPageExample as ComponentType,
    "activity-feed:ActivityFeedExample": d12.ActivityFeedExample as ComponentType,
    "activity-feed:ActivityFeedDivided": d12.ActivityFeedDivided as ComponentType,
    "activity-feed:ActivityFeedConnected": d12.ActivityFeedConnected as ComponentType,
    "activity-feed:ActivityFeedSpaced": d12.ActivityFeedSpaced as ComponentType,
    "activity-feed:MessagesDivided": d12.MessagesDivided as ComponentType,
    "activity-feed:MessagesConnected": d12.MessagesConnected as ComponentType,
    "activity-feed:MessagesSpaced": d12.MessagesSpaced as ComponentType,
    "ai-elements:AIChatExample": d13.AIChatExample as ComponentType,
    "ai-elements:StreamingExample": d13.StreamingExample as ComponentType,
    "ai-elements:ConversationExample": d13.ConversationExample as ComponentType,
    "ai-elements:MessageExample": d13.MessageExample as ComponentType,
    "ai-elements:ResponseExample": d13.ResponseExample as ComponentType,
    "ai-elements:ReasoningExample": d13.ReasoningExample as ComponentType,
    "ai-elements:ToolCallExample": d13.ToolCallExample as ComponentType,
    "ai-elements:SourcesExample": d13.SourcesExample as ComponentType,
    "ai-elements:SuggestionsExample": d13.SuggestionsExample as ComponentType,
    "ai-elements:PromptInputExample": d13.PromptInputExample as ComponentType,
    "ai-elements:PromptInputStreamingExample": d13.PromptInputStreamingExample as ComponentType,
    "ai-elements:ModelSelectorExample": d13.ModelSelectorExample as ComponentType,
    "ai-elements:BranchExample": d13.BranchExample as ComponentType,
    "alerts:AlertExample": d14.AlertExample as ComponentType,
    "alerts:FloatingDefault": d14.FloatingDefault as ComponentType,
    "alerts:FloatingBrand": d14.FloatingBrand as ComponentType,
    "alerts:FloatingGray": d14.FloatingGray as ComponentType,
    "alerts:FloatingError": d14.FloatingError as ComponentType,
    "alerts:FloatingWarning": d14.FloatingWarning as ComponentType,
    "alerts:FloatingSuccess": d14.FloatingSuccess as ComponentType,
    "alerts:FullWidthDefault": d14.FullWidthDefault as ComponentType,
    "alerts:FullWidthBrand": d14.FullWidthBrand as ComponentType,
    "alerts:FullWidthGray": d14.FullWidthGray as ComponentType,
    "alerts:FullWidthError": d14.FullWidthError as ComponentType,
    "alerts:FullWidthWarning": d14.FullWidthWarning as ComponentType,
    "alerts:FullWidthSuccess": d14.FullWidthSuccess as ComponentType,
    "header-navigation:HeaderNavigationExample": d15.HeaderNavigationExample as ComponentType,
    "header-navigation:Simple": d15.Simple as ComponentType,
    "header-navigation:DualTier": d15.DualTier as ComponentType,
    "sidebar-navigation:SidebarNavigationExample": d16.SidebarNavigationExample as ComponentType,
    "sidebar-navigation:Simple": d16.Simple as ComponentType,
    "sidebar-navigation:CustomBrand": d16.CustomBrand as ComponentType,
    "sidebar-navigation:DualTier": d16.DualTier as ComponentType,
    "sidebar-navigation:Slim": d16.Slim as ComponentType,
    "sidebar-navigation:SectionsDividers": d16.SectionsDividers as ComponentType,
    "sidebar-navigation:SectionsSubheadings": d16.SectionsSubheadings as ComponentType,
    "sidebar-navigation:ProgressBar": d16.ProgressBar as ComponentType,
    "sidebar-navigation:ProgressCircle": d16.ProgressCircle as ComponentType,
    "sidebar-navigation:Image": d16.Image as ComponentType,
    "sidebar-navigation:CookiePreferences": d16.CookiePreferences as ComponentType,
    "sidebar-navigation:ReferralLink": d16.ReferralLink as ComponentType,
    "sidebar-navigation:OnboardingSteps": d16.OnboardingSteps as ComponentType,
    "sidebar-navigation:UpgradeCTA": d16.UpgradeCTA as ComponentType,
    "sidebar-navigation:SupportCTA": d16.SupportCTA as ComponentType,
    "sidebar-navigation:EventCTA": d16.EventCTA as ComponentType,
    "sidebar-navigation:Message": d16.Message as ComponentType,
    "sidebar-navigation:CurrentProjects": d16.CurrentProjects as ComponentType,
    "sidebar-navigation:FreeTrialCTA": d16.FreeTrialCTA as ComponentType,
    "sidebar-navigation:QRCode": d16.QRCode as ComponentType,
    "breadcrumbs:BreadcrumbsExample": d17.BreadcrumbsExample as ComponentType,
    "breadcrumbs:BreadcrumbsText": d17.BreadcrumbsText as ComponentType,
    "breadcrumbs:BreadcrumbsTextWithLine": d17.BreadcrumbsTextWithLine as ComponentType,
    "breadcrumbs:BreadcrumbsButton": d17.BreadcrumbsButton as ComponentType,
    "breadcrumbs:AccountButtonChevron": d17.AccountButtonChevron as ComponentType,
    "breadcrumbs:AccountButtonSlash": d17.AccountButtonSlash as ComponentType,
    "callout:CalloutExample": d18.CalloutExample as ComponentType,
    "callout:Tones": d18.Tones as ComponentType,
    "callout:WithoutTitle": d18.WithoutTitle as ComponentType,
    "callout:WithoutIcon": d18.WithoutIcon as ComponentType,
    "card-headers:CardHeaderExample": d19.CardHeaderExample as ComponentType,
    "card-headers:CardHeaderWithBadge": d19.CardHeaderWithBadge as ComponentType,
    "card-headers:CardHeaderWithAvatarAndBadge": d19.CardHeaderWithAvatarAndBadge as ComponentType,
    "carousel:CarouselExample": d20.CarouselExample as ComponentType,
    "carousel:CarouselMd": d20.CarouselMd as ComponentType,
    "carousel:CarouselLg": d20.CarouselLg as ComponentType,
    "activity-gauges:ActivityGaugeXs": d21.ActivityGaugeXs as ComponentType,
    "activity-gauges:ActivityGaugeSm": d21.ActivityGaugeSm as ComponentType,
    "activity-gauges:ActivityGaugeMd": d21.ActivityGaugeMd as ComponentType,
    "activity-gauges:ActivityGaugeLg": d21.ActivityGaugeLg as ComponentType,
    "activity-gauges:ActivityGaugeExample": d21.ActivityGaugeExample as ComponentType,
    "area-charts:AreaChartStacked": d22.AreaChartStacked as ComponentType,
    "area-charts:AreaChartGradient": d22.AreaChartGradient as ComponentType,
    "area-charts:AreaChartStepped": d22.AreaChartStepped as ComponentType,
    "area-charts:AreaChartBrush": d22.AreaChartBrush as ComponentType,
    "area-charts:AreaChartSmallMultiples": d22.AreaChartSmallMultiples as ComponentType,
    "area-charts:AreaChartExample": d22.AreaChartExample as ComponentType,
    "combined-charts:BarLineComposed": d23.BarLineComposed as ComponentType,
    "combined-charts:DualAxisChart": d23.DualAxisChart as ComponentType,
    "combined-charts:BarWithTargetLine": d23.BarWithTargetLine as ComponentType,
    "combined-charts:WaterfallChart": d23.WaterfallChart as ComponentType,
    "combined-charts:FunnelChartExample": d23.FunnelChartExample as ComponentType,
    "combined-charts:CombinedChartExample": d23.CombinedChartExample as ComponentType,
    "line-bar-charts:LineChart01": d24.LineChart01 as ComponentType,
    "line-bar-charts:LineChart02": d24.LineChart02 as ComponentType,
    "line-bar-charts:LineChart03": d24.LineChart03 as ComponentType,
    "line-bar-charts:LineChart04": d24.LineChart04 as ComponentType,
    "line-bar-charts:BarChart01": d24.BarChart01 as ComponentType,
    "line-bar-charts:BarChart02": d24.BarChart02 as ComponentType,
    "line-bar-charts:BarChart03": d24.BarChart03 as ComponentType,
    "line-bar-charts:LineChartExample": d24.LineChartExample as ComponentType,
    "pie-charts:PieChartXxl": d25.PieChartXxl as ComponentType,
    "pie-charts:PieChartXs": d25.PieChartXs as ComponentType,
    "pie-charts:PieChartSm": d25.PieChartSm as ComponentType,
    "pie-charts:PieChartMd": d25.PieChartMd as ComponentType,
    "pie-charts:PieChartLg": d25.PieChartLg as ComponentType,
    "pie-charts:PieChartExample": d25.PieChartExample as ComponentType,
    "radar-charts:RadarChart": d26.RadarChart as ComponentType,
    "radar-charts:RadarChartExample": d26.RadarChartExample as ComponentType,
    "scatter-bubble-charts:ScatterChartBasic": d27.ScatterChartBasic as ComponentType,
    "scatter-bubble-charts:BubbleChart": d27.BubbleChart as ComponentType,
    "scatter-bubble-charts:ScatterChartRegression": d27.ScatterChartRegression as ComponentType,
    "scatter-bubble-charts:ScatterChartCategorical": d27.ScatterChartCategorical as ComponentType,
    "scatter-bubble-charts:ScatterChartExample": d27.ScatterChartExample as ComponentType,
    "sparklines:LineSparkline": d28.LineSparkline as ComponentType,
    "sparklines:AreaSparkline": d28.AreaSparkline as ComponentType,
    "sparklines:BarSparkline": d28.BarSparkline as ComponentType,
    "sparklines:NegativeTrendSparkline": d28.NegativeTrendSparkline as ComponentType,
    "sparklines:SparklineTableCells": d28.SparklineTableCells as ComponentType,
    "sparklines:SparklineInMetricCards": d28.SparklineInMetricCards as ComponentType,
    "sparklines:SparklineExample": d28.SparklineExample as ComponentType,
    "code-editor:CodeEditorExample": d29.CodeEditorExample as ComponentType,
    "code-editor:JsonEditor": d29.JsonEditor as ComponentType,
    "code-editor:ReadOnlyWithDiagnostics": d29.ReadOnlyWithDiagnostics as ComponentType,
    "code-editor:Minimal": d29.Minimal as ComponentType,
    "code-snippet:CodeSnippetExample": d30.CodeSnippetExample as ComponentType,
    "code-snippet:WithLineNumber": d30.WithLineNumber as ComponentType,
    "code-snippet:WithoutLineNumber": d30.WithoutLineNumber as ComponentType,
    "code-snippet:ShowMore": d30.ShowMore as ComponentType,
    "code-snippet:WithTabs": d30.WithTabs as ComponentType,
    "color-picker:ColorPickerExample": d31.ColorPickerExample as ComponentType,
    "color-picker:ColorPicker": d31.ColorPicker as ComponentType,
    "color-picker:ColorSwatchPicker": d31.ColorSwatchPicker as ComponentType,
    "color-picker:SavedSwatchesSmall": d31.SavedSwatchesSmall as ComponentType,
    "color-picker:SavedSwatchesMedium": d31.SavedSwatchesMedium as ComponentType,
    "color-picker:BrandSwatches": d31.BrandSwatches as ComponentType,
    "color-picker:GraySwatches": d31.GraySwatches as ComponentType,
    "color-picker:MinimalPicker": d31.MinimalPicker as ComponentType,
    "color-picker:HueSlider": d31.HueSlider as ComponentType,
    "color-picker:TransparencySlider": d31.TransparencySlider as ComponentType,
    "color-picker:PalettePicker": d31.PalettePicker as ComponentType,
    "command-menu:CommandMenuExample": d32.CommandMenuExample as ComponentType,
    "command-menu:Users": d32.Users as ComponentType,
    "command-menu:UsersStacked": d32.UsersStacked as ComponentType,
    "command-menu:Actions": d32.Actions as ComponentType,
    "command-menu:ActionsStacked": d32.ActionsStacked as ComponentType,
    "command-menu:EmptyState": d32.EmptyState as ComponentType,
    "command-menu:UsersMenu": d32.UsersMenu as ComponentType,
    "command-menu:UsersMenuStacked": d32.UsersMenuStacked as ComponentType,
    "command-menu:IntegrationsMenu": d32.IntegrationsMenu as ComponentType,
    "command-menu:IntegrationsMenuStacked": d32.IntegrationsMenuStacked as ComponentType,
    "confirm-dialog:ConfirmDialogExample": d33.ConfirmDialogExample as ComponentType,
    "confirm-dialog:Destructive": d33.Destructive as ComponentType,
    "confirm-dialog:AsyncConfirm": d33.AsyncConfirm as ComponentType,
    "content-divider:ContentDividerExample": d34.ContentDividerExample as ComponentType,
    "content-divider:SingleLine": d34.SingleLine as ComponentType,
    "content-divider:DualLine": d34.DualLine as ComponentType,
    "content-divider:BackgroundFill": d34.BackgroundFill as ComponentType,
    "data-table:BasicSortable": d35.BasicSortable as ComponentType,
    "data-table:FiltersAndColumnVisibility": d35.FiltersAndColumnVisibility as ComponentType,
    "data-table:SelectionAndBulkActions": d35.SelectionAndBulkActions as ComponentType,
    "data-table:Virtualized5000Rows": d35.Virtualized5000Rows as ComponentType,
    "data-table:ServerSideMode": d35.ServerSideMode as ComponentType,
    "data-table:PinnedColumnsStickyHeader": d35.PinnedColumnsStickyHeader as ComponentType,
    "data-table:ResizableColumns": d35.ResizableColumns as ComponentType,
    "calendar:CalendarExample": d36.CalendarExample as ComponentType,
    "calendar:CalendarMonthView": d36.CalendarMonthView as ComponentType,
    "calendar:CalendarWeekView": d36.CalendarWeekView as ComponentType,
    "calendar:CalendarDayView": d36.CalendarDayView as ComponentType,
    "date-pickers:DatePickerExample": d37.DatePickerExample as ComponentType,
    "date-pickers:DatePicker": d37.DatePicker as ComponentType,
    "date-pickers:DateTimePicker": d37.DateTimePicker as ComponentType,
    "date-pickers:DateRangePickerWithPresets": d37.DateRangePickerWithPresets as ComponentType,
    "date-pickers:Calendar": d37.Calendar as ComponentType,
    "date-pickers:CalendarCard": d37.CalendarCard as ComponentType,
    "date-pickers:RangeCalendar": d37.RangeCalendar as ComponentType,
    "date-pickers:RangeCalendarCard": d37.RangeCalendarCard as ComponentType,
    "description-list:DescriptionListExample": d38.DescriptionListExample as ComponentType,
    "description-list:Horizontal": d38.Horizontal as ComponentType,
    "description-list:Stacked": d38.Stacked as ComponentType,
    "empty-state:EmptyStateExample": d39.EmptyStateExample as ComponentType,
    "empty-state:FeaturedIcon": d39.FeaturedIcon as ComponentType,
    "empty-state:Illustration": d39.Illustration as ComponentType,
    "empty-state:FileIcon": d39.FileIcon as ComponentType,
    "empty-state:AvatarRadius": d39.AvatarRadius as ComponentType,
    "empty-state:AvatarRow": d39.AvatarRow as ComponentType,
    "empty-state:AvatarGrid": d39.AvatarGrid as ComponentType,
    "file-upload:FileUploadExample": d40.FileUploadExample as ComponentType,
    "file-upload:ProgressBar": d40.ProgressBar as ComponentType,
    "file-upload:ProgressFill": d40.ProgressFill as ComponentType,
    "file-upload:Disabled": d40.Disabled as ComponentType,
    "file-upload:AcceptImageOnly": d40.AcceptImageOnly as ComponentType,
    "file-upload:MaxSizeLimit": d40.MaxSizeLimit as ComponentType,
    "filter-bars:FilterBarExample": d41.FilterBarExample as ComponentType,
    "filter-bars:Simple": d41.Simple as ComponentType,
    "filter-bars:TabsAndSearch": d41.TabsAndSearch as ComponentType,
    "filter-bars:TabsAndDatePicker": d41.TabsAndDatePicker as ComponentType,
    "filter-bars:DateFilters": d41.DateFilters as ComponentType,
    "filter-bars:Dropdowns": d41.Dropdowns as ComponentType,
    "filter-bars:DropdownsAndDatePicker": d41.DropdownsAndDatePicker as ComponentType,
    "filter-bars:AdvancedFilterInactive": d41.AdvancedFilterInactive as ComponentType,
    "filter-bars:AdvancedFilterActive": d41.AdvancedFilterActive as ComponentType,
    "filter-bars:FilterDropdownEmptyState": d41.FilterDropdownEmptyState as ComponentType,
    "filter-bars:FilterDropdownInactive": d41.FilterDropdownInactive as ComponentType,
    "filter-bars:FilterDropdownActive": d41.FilterDropdownActive as ComponentType,
    "filter-bars:FiltersAdvancedEmptyStateMenu": d41.FiltersAdvancedEmptyStateMenu as ComponentType,
    "filter-bars:FiltersAdvancedActiveMenu": d41.FiltersAdvancedActiveMenu as ComponentType,
    "gantt:GanttExample": d42.GanttExample as ComponentType,
    "gantt:DayZoom": d42.DayZoom as ComponentType,
    "gantt:MonthZoomWithMarkers": d42.MonthZoomWithMarkers as ComponentType,
    "gantt:ReadOnly": d42.ReadOnly as ComponentType,
    "gradient-picker:GradientPickerExample": d43.GradientPickerExample as ComponentType,
    "gradient-picker:GradientPicker": d43.GradientPicker as ComponentType,
    "image-picker:ImagePickerExample": d44.ImagePickerExample as ComponentType,
    "image-picker:ImagePicker": d44.ImagePicker as ComponentType,
    "inline-cta:InlineCTAExample": d45.InlineCTAExample as ComponentType,
    "inline-cta:Actions": d45.Actions as ComponentType,
    "inline-cta:EmailField": d45.EmailField as ComponentType,
    "inline-cta:ChangePlan": d45.ChangePlan as ComponentType,
    "inline-cta:UpgradePlan": d45.UpgradePlan as ComponentType,
    "inline-cta:PaymentMethod": d45.PaymentMethod as ComponentType,
    "inline-cta:Receipt": d45.Receipt as ComponentType,
    "kanban:KanbanExample": d46.KanbanExample as ComponentType,
    "kanban:CustomCards": d46.CustomCards as ComponentType,
    "kanban:CollapsibleColumns": d46.CollapsibleColumns as ComponentType,
    "loading-indicator:LoadingIndicatorExample": d47.LoadingIndicatorExample as ComponentType,
    "loading-indicator:LineSimple": d47.LineSimple as ComponentType,
    "loading-indicator:LineSimpleWithLabel": d47.LineSimpleWithLabel as ComponentType,
    "loading-indicator:LineSpinner": d47.LineSpinner as ComponentType,
    "loading-indicator:LineSpinnerWithLabel": d47.LineSpinnerWithLabel as ComponentType,
    "loading-indicator:DotCircle": d47.DotCircle as ComponentType,
    "loading-indicator:DotCircleWithLabel": d47.DotCircleWithLabel as ComponentType,
    "loading-indicator:Sizes": d47.Sizes as ComponentType,
    "loading-indicator:InlineXs": d47.InlineXs as ComponentType,
    "messaging:MessagingExample": d48.MessagingExample as ComponentType,
    "messaging:MessageStatus": d48.MessageStatus as ComponentType,
    "messaging:MessageActionMinimal": d48.MessageActionMinimal as ComponentType,
    "messaging:MessageActionTextarea": d48.MessageActionTextarea as ComponentType,
    "messaging:MessageActionAdvanced": d48.MessageActionAdvanced as ComponentType,
    "messaging:MessageSimple": d48.MessageSimple as ComponentType,
    "messaging:MessageReactions": d48.MessageReactions as ComponentType,
    "messaging:MessageReply": d48.MessageReply as ComponentType,
    "messaging:MessageAttachment": d48.MessageAttachment as ComponentType,
    "messaging:MessageAudio": d48.MessageAudio as ComponentType,
    "messaging:MessageImage": d48.MessageImage as ComponentType,
    "messaging:MessageLinkPreview": d48.MessageLinkPreview as ComponentType,
    "messaging:MessageLinkMinimal": d48.MessageLinkMinimal as ComponentType,
    "messaging:MessageWriting": d48.MessageWriting as ComponentType,
    "metrics:MetricsExample": d49.MetricsExample as ComponentType,
    "metrics:Simple": d49.Simple as ComponentType,
    "metrics:SimpleNoChange": d49.SimpleNoChange as ComponentType,
    "metrics:SimpleActions": d49.SimpleActions as ComponentType,
    "metrics:MetricsIcon01": d49.MetricsIcon01 as ComponentType,
    "metrics:MetricsIconActions01": d49.MetricsIconActions01 as ComponentType,
    "metrics:MetricsIcon02": d49.MetricsIcon02 as ComponentType,
    "metrics:MetricsIconActions02": d49.MetricsIconActions02 as ComponentType,
    "metrics:MetricsIcon03": d49.MetricsIcon03 as ComponentType,
    "metrics:MetricsIconActions03": d49.MetricsIconActions03 as ComponentType,
    "metrics:MetricsIcon04": d49.MetricsIcon04 as ComponentType,
    "metrics:MetricsIconActions04": d49.MetricsIconActions04 as ComponentType,
    "metrics:Chart01": d49.Chart01 as ComponentType,
    "metrics:ChartActions01": d49.ChartActions01 as ComponentType,
    "metrics:Chart02": d49.Chart02 as ComponentType,
    "metrics:ChartActions02": d49.ChartActions02 as ComponentType,
    "metrics:Chart03": d49.Chart03 as ComponentType,
    "metrics:ChartActions03": d49.ChartActions03 as ComponentType,
    "metrics:Chart04": d49.Chart04 as ComponentType,
    "metrics:ChartActions04": d49.ChartActions04 as ComponentType,
    "modals:ModalExample": d50.ModalExample as ComponentType,
    "modals:StackedLeftAligned": d50.StackedLeftAligned as ComponentType,
    "modals:WarningStackedLeftAligned": d50.WarningStackedLeftAligned as ComponentType,
    "modals:DestructiveStackedLeftAligned": d50.DestructiveStackedLeftAligned as ComponentType,
    "modals:ConfirmDialog": d50.ConfirmDialog as ComponentType,
    "modals:Horizontal": d50.Horizontal as ComponentType,
    "modals:WarningHorizontal": d50.WarningHorizontal as ComponentType,
    "modals:DestructiveHorizontal": d50.DestructiveHorizontal as ComponentType,
    "modals:Login": d50.Login as ComponentType,
    "modals:Signup01": d50.Signup01 as ComponentType,
    "modals:Signup02": d50.Signup02 as ComponentType,
    "modals:Checkboxes": d50.Checkboxes as ComponentType,
    "modals:Toggles": d50.Toggles as ComponentType,
    "modals:LinkField": d50.LinkField as ComponentType,
    "modals:Dropdown": d50.Dropdown as ComponentType,
    "modals:InputField": d50.InputField as ComponentType,
    "modals:Labels": d50.Labels as ComponentType,
    "modals:AccessRequest": d50.AccessRequest as ComponentType,
    "modals:EmailInvite": d50.EmailInvite as ComponentType,
    "modals:UserInvite": d50.UserInvite as ComponentType,
    "modals:StackedWithTeam": d50.StackedWithTeam as ComponentType,
    "modals:StackedWithTeamAndLink": d50.StackedWithTeamAndLink as ComponentType,
    "modals:StackedWithTeamAndInvites": d50.StackedWithTeamAndInvites as ComponentType,
    "modals:VerificationCode": d50.VerificationCode as ComponentType,
    "modals:TwoFactorCode": d50.TwoFactorCode as ComponentType,
    "modals:PasswordPrompt": d50.PasswordPrompt as ComponentType,
    "modals:CenteredPhoto": d50.CenteredPhoto as ComponentType,
    "modals:CenteredPhotoCarousel": d50.CenteredPhotoCarousel as ComponentType,
    "modals:CenteredVideoCarousel": d50.CenteredVideoCarousel as ComponentType,
    "modals:PaymentDetails": d50.PaymentDetails as ComponentType,
    "modals:PaymentDetailsWithImage": d50.PaymentDetailsWithImage as ComponentType,
    "modals:Plan01": d50.Plan01 as ComponentType,
    "modals:Plan02": d50.Plan02 as ComponentType,
    "modals:PaymentMethod": d50.PaymentMethod as ComponentType,
    "modals:DatePicker": d50.DatePicker as ComponentType,
    "modals:FileUpload": d50.FileUpload as ComponentType,
    "modals:ProfileSettings": d50.ProfileSettings as ComponentType,
    "modals:UserSelection": d50.UserSelection as ComponentType,
    "modals:Form01": d50.Form01 as ComponentType,
    "modals:Form02": d50.Form02 as ComponentType,
    "modals:ImageCrop": d50.ImageCrop as ComponentType,
    "modals:CalendarEvent": d50.CalendarEvent as ComponentType,
    "modals:BannerAppearance": d50.BannerAppearance as ComponentType,
    "modals:AppearanceSettings": d50.AppearanceSettings as ComponentType,
    "modals:AIAssistant": d50.AIAssistant as ComponentType,
    "modals:UserSettings": d50.UserSettings as ComponentType,
    "modals:NewProject": d50.NewProject as ComponentType,
    "modals:TextEditor": d50.TextEditor as ComponentType,
    "modals:ShareProject": d50.ShareProject as ComponentType,
    "modals:CreateEvent": d50.CreateEvent as ComponentType,
    "modals:Integration": d50.Integration as ComponentType,
    "modals:NewMessageEmptyState": d50.NewMessageEmptyState as ComponentType,
    "modals:NewMessageFilled": d50.NewMessageFilled as ComponentType,
    "notifications:NotificationExample": d51.NotificationExample as ComponentType,
    "notifications:IconDefault": d51.IconDefault as ComponentType,
    "notifications:IconGray": d51.IconGray as ComponentType,
    "notifications:IconBrand": d51.IconBrand as ComponentType,
    "notifications:IconError": d51.IconError as ComponentType,
    "notifications:IconWarning": d51.IconWarning as ComponentType,
    "notifications:IconSuccess": d51.IconSuccess as ComponentType,
    "notifications:ProgressNotification": d51.ProgressNotification as ComponentType,
    "notifications:ImageNotification": d51.ImageNotification as ComponentType,
    "notifications:AvatarNotification": d51.AvatarNotification as ComponentType,
    "page-headers:PageHeaderExample": d52.PageHeaderExample as ComponentType,
    "page-headers:Simple": d52.Simple as ComponentType,
    "page-headers:Avatar": d52.Avatar as ComponentType,
    "page-headers:BannerSimple": d52.BannerSimple as ComponentType,
    "page-headers:BannerAvatar": d52.BannerAvatar as ComponentType,
    "page-headers:BannerSimpleCentered": d52.BannerSimpleCentered as ComponentType,
    "page-headers:BannerAvatarCentered": d52.BannerAvatarCentered as ComponentType,
    "pagination:PaginationExample": d53.PaginationExample as ComponentType,
    "pagination:PageDefault": d53.PageDefault as ComponentType,
    "pagination:PageMinimalCenter": d53.PageMinimalCenter as ComponentType,
    "pagination:CardDefault": d53.CardDefault as ComponentType,
    "pagination:CardMinimalRightAligned": d53.CardMinimalRightAligned as ComponentType,
    "pagination:CardMinimalCenterAligned": d53.CardMinimalCenterAligned as ComponentType,
    "pagination:CardMinimalLeftAligned": d53.CardMinimalLeftAligned as ComponentType,
    "pagination:ButtonGroupRightAligned": d53.ButtonGroupRightAligned as ComponentType,
    "pagination:ButtonGroupCenterAligned": d53.ButtonGroupCenterAligned as ComponentType,
    "pagination:ButtonGroupLeftAligned": d53.ButtonGroupLeftAligned as ComponentType,
    "pagination:CardAdvanced": d53.CardAdvanced as ComponentType,
    "pagination:CardAdvancedCenter": d53.CardAdvancedCenter as ComponentType,
    "pagination:PaginationDot": d53.PaginationDot as ComponentType,
    "pagination:Cursor": d53.Cursor as ComponentType,
    "pagination:PaginationLine": d53.PaginationLine as ComponentType,
    "progress-steps:ProgressStepsExample": d54.ProgressStepsExample as ComponentType,
    "progress-steps:IconCentered": d54.IconCentered as ComponentType,
    "progress-steps:IconCenteredWithNumber": d54.IconCenteredWithNumber as ComponentType,
    "progress-steps:FeaturedIconCentered": d54.FeaturedIconCentered as ComponentType,
    "progress-steps:IconWithText": d54.IconWithText as ComponentType,
    "progress-steps:IconWithNumber": d54.IconWithNumber as ComponentType,
    "progress-steps:FeaturedIconWithText": d54.FeaturedIconWithText as ComponentType,
    "progress-steps:MinimalIcons": d54.MinimalIcons as ComponentType,
    "progress-steps:MinimalIconsConnected": d54.MinimalIconsConnected as ComponentType,
    "progress-steps:Interactive": d54.Interactive as ComponentType,
    "progress-steps:WithStepContent": d54.WithStepContent as ComponentType,
    "progress-steps:TextWithLine": d54.TextWithLine as ComponentType,
    "resizable:ResizableExample": d55.ResizableExample as ComponentType,
    "resizable:Vertical": d55.Vertical as ComponentType,
    "resizable:CollapsibleSidebar": d55.CollapsibleSidebar as ComponentType,
    "resizable:Nested": d55.Nested as ComponentType,
    "scroll-area:ScrollAreaExample": d56.ScrollAreaExample as ComponentType,
    "scroll-area:Horizontal": d56.Horizontal as ComponentType,
    "scroll-area:BothAxes": d56.BothAxes as ComponentType,
    "scroll-area:FadeEdges": d56.FadeEdges as ComponentType,
    "section-footers:SectionFooterExample": d57.SectionFooterExample as ComponentType,
    "section-footers:SectionFooterButtonGroup": d57.SectionFooterButtonGroup as ComponentType,
    "section-footers:SectionFooter": d57.SectionFooter as ComponentType,
    "section-footers:SectionFooterCardButtonGroup": d57.SectionFooterCardButtonGroup as ComponentType,
    "section-footers:SectionFooterCard": d57.SectionFooterCard as ComponentType,
    "section-headers:SectionHeaderExample": d58.SectionHeaderExample as ComponentType,
    "section-headers:SectionHeaderButtons": d58.SectionHeaderButtons as ComponentType,
    "section-headers:SectionHeaderSearchInput": d58.SectionHeaderSearchInput as ComponentType,
    "section-headers:SectionHeaderButtonGroup": d58.SectionHeaderButtonGroup as ComponentType,
    "section-headers:SectionHeaderButtonsWithTabs": d58.SectionHeaderButtonsWithTabs as ComponentType,
    "section-headers:SectionHeaderSearchInputWithTabs": d58.SectionHeaderSearchInputWithTabs as ComponentType,
    "section-headers:SectionHeaderButtonGroupsWithTabs": d58.SectionHeaderButtonGroupsWithTabs as ComponentType,
    "slideout-menus:DrawerExample": d59.DrawerExample as ComponentType,
    "slideout-menus:PlaceholderMenu": d59.PlaceholderMenu as ComponentType,
    "slideout-menus:UserProfileMenu": d59.UserProfileMenu as ComponentType,
    "slideout-menus:MessagesMenu": d59.MessagesMenu as ComponentType,
    "slideout-menus:MessageChatMenu": d59.MessageChatMenu as ComponentType,
    "slideout-menus:PaymentMethodMenu": d59.PaymentMethodMenu as ComponentType,
    "slideout-menus:PaymentDetailsMenu": d59.PaymentDetailsMenu as ComponentType,
    "slideout-menus:PlanMenu": d59.PlanMenu as ComponentType,
    "slideout-menus:TeamMembersMenu": d59.TeamMembersMenu as ComponentType,
    "slideout-menus:FiltersMenu": d59.FiltersMenu as ComponentType,
    "slideout-menus:FiltersAdvancedEmptyStateMenu": d59.FiltersAdvancedEmptyStateMenu as ComponentType,
    "slideout-menus:FiltersAdvancedActiveMenu": d59.FiltersAdvancedActiveMenu as ComponentType,
    "slideout-menus:FileUploadMenu": d59.FileUploadMenu as ComponentType,
    "slideout-menus:LabelsMenu": d59.LabelsMenu as ComponentType,
    "slideout-menus:ProjectDetailsMenu": d59.ProjectDetailsMenu as ComponentType,
    "slideout-menus:NotificationSettingsCheckboxMenu": d59.NotificationSettingsCheckboxMenu as ComponentType,
    "slideout-menus:NotificationSettingsButtonMenu": d59.NotificationSettingsButtonMenu as ComponentType,
    "slideout-menus:NotificationsMenu": d59.NotificationsMenu as ComponentType,
    "slideout-menus:OrderSummaryMenu": d59.OrderSummaryMenu as ComponentType,
    "slideout-menus:CalendarEventMenu": d59.CalendarEventMenu as ComponentType,
    "slideout-menus:UserSettingsMenu": d59.UserSettingsMenu as ComponentType,
    "slideout-menus:AIAssistantMenu": d59.AIAssistantMenu as ComponentType,
    "slideout-menus:AIAssistantMessageMenu": d59.AIAssistantMessageMenu as ComponentType,
    "slideout-menus:ShareProjectMenu": d59.ShareProjectMenu as ComponentType,
    "slideout-menus:CreateEventMenu": d59.CreateEventMenu as ComponentType,
    "slideout-menus:IntegrationMenu": d59.IntegrationMenu as ComponentType,
    "sortable-list:SortableListExample": d60.SortableListExample as ComponentType,
    "sortable-list:SettingsSections": d60.SettingsSections as ComponentType,
    "sortable-list:CardsVariant": d60.CardsVariant as ComponentType,
    "stepper:CheckoutExample": d61.CheckoutExample as ComponentType,
    "stepper:VerticalLayout": d61.VerticalLayout as ComponentType,
    "stepper:NonLinear": d61.NonLinear as ComponentType,
    "table:TableExample": d62.TableExample as ComponentType,
    "table:TableSmallSizeExample": d62.TableSmallSizeExample as ComponentType,
    "table:DividerLine01": d62.DividerLine01 as ComponentType,
    "table:AlternatingFills01": d62.AlternatingFills01 as ComponentType,
    "table:DividerLine02": d62.DividerLine02 as ComponentType,
    "table:AlternatingFills02": d62.AlternatingFills02 as ComponentType,
    "table:DividerLine03": d62.DividerLine03 as ComponentType,
    "table:AlternatingFills03": d62.AlternatingFills03 as ComponentType,
    "table:DividerLine04": d62.DividerLine04 as ComponentType,
    "table:AlternatingFills04": d62.AlternatingFills04 as ComponentType,
    "table:StaticUsage": d62.StaticUsage as ComponentType,
    "table:VisuallyHiddenColumnLabel": d62.VisuallyHiddenColumnLabel as ComponentType,
    "table:NoVendorsFound": d62.NoVendorsFound as ComponentType,
    "table:SomethingWentWrong": d62.SomethingWentWrong as ComponentType,
    "table:NoUsersFound": d62.NoUsersFound as ComponentType,
    "table:AddFirstIntegration": d62.AddFirstIntegration as ComponentType,
    "table:InviteFirstUser": d62.InviteFirstUser as ComponentType,
    "table:OfflineState": d62.OfflineState as ComponentType,
    "tabs:TabsExample": d63.TabsExample as ComponentType,
    "tabs:ButtonBrandHorizontal": d63.ButtonBrandHorizontal as ComponentType,
    "tabs:ButtonGrayHorizontal": d63.ButtonGrayHorizontal as ComponentType,
    "tabs:ButtonBorderHorizontal": d63.ButtonBorderHorizontal as ComponentType,
    "tabs:ButtonMinimalHorizontal": d63.ButtonMinimalHorizontal as ComponentType,
    "tabs:Underline": d63.Underline as ComponentType,
    "tabs:ButtonBrandVertical": d63.ButtonBrandVertical as ComponentType,
    "tabs:ButtonGrayVertical": d63.ButtonGrayVertical as ComponentType,
    "tabs:ButtonBorderVertical": d63.ButtonBorderVertical as ComponentType,
    "tabs:ButtonMinimalVertical": d63.ButtonMinimalVertical as ComponentType,
    "tabs:Line": d63.Line as ComponentType,
    "timeline:OrderTracking": d64.OrderTracking as ComponentType,
    "timeline:ReleaseHistory": d64.ReleaseHistory as ComponentType,
    "timeline:Horizontal": d64.Horizontal as ComponentType,
    "timeline:PlainDots": d64.PlainDots as ComponentType,
    "tree-view:TreeViewExample": d65.TreeViewExample as ComponentType,
    "tree-view:SimpleSm": d65.SimpleSm as ComponentType,
    "tree-view:SimpleMd": d65.SimpleMd as ComponentType,
    "tree-view:AdvancedSm": d65.AdvancedSm as ComponentType,
    "tree-view:AdvancedMd": d65.AdvancedMd as ComponentType,
    "avatar:AvatarExample": d66.AvatarExample as ComponentType,
    "avatar:Avatar": d66.Avatar as ComponentType,
    "avatar:BorderExample": d66.BorderExample as ComponentType,
    "avatar:StatusIndicatorExample": d66.StatusIndicatorExample as ComponentType,
    "avatar:CompanyLogoExample": d66.CompanyLogoExample as ComponentType,
    "avatar:VerifiedBadgeExample": d66.VerifiedBadgeExample as ComponentType,
    "avatar:PlaceholderExample": d66.PlaceholderExample as ComponentType,
    "avatar:InitialsExample": d66.InitialsExample as ComponentType,
    "avatar:LabelGroupExample": d66.LabelGroupExample as ComponentType,
    "avatar:GroupExample": d66.GroupExample as ComponentType,
    "avatar:ProfilePhoto": d66.ProfilePhoto as ComponentType,
    "avatar:ProfilePhotoPlaceholderExample": d66.ProfilePhotoPlaceholderExample as ComponentType,
    "avatar:ProfilePhotoInitialsExample": d66.ProfilePhotoInitialsExample as ComponentType,
    "badge-groups:BadgeGroupExample": d67.BadgeGroupExample as ComponentType,
    "badge-groups:PillColorLeadingGray": d67.PillColorLeadingGray as ComponentType,
    "badge-groups:PillColorLeadingBrand": d67.PillColorLeadingBrand as ComponentType,
    "badge-groups:PillColorLeadingError": d67.PillColorLeadingError as ComponentType,
    "badge-groups:PillColorLeadingWarning": d67.PillColorLeadingWarning as ComponentType,
    "badge-groups:PillColorLeadingSuccess": d67.PillColorLeadingSuccess as ComponentType,
    "badge-groups:PillColorTrailingGray": d67.PillColorTrailingGray as ComponentType,
    "badge-groups:PillColorTrailingBrand": d67.PillColorTrailingBrand as ComponentType,
    "badge-groups:PillColorTrailingError": d67.PillColorTrailingError as ComponentType,
    "badge-groups:PillColorTrailingWarning": d67.PillColorTrailingWarning as ComponentType,
    "badge-groups:PillColorTrailingSuccess": d67.PillColorTrailingSuccess as ComponentType,
    "badge-groups:ModernLeadingGray": d67.ModernLeadingGray as ComponentType,
    "badge-groups:ModernLeadingBrand": d67.ModernLeadingBrand as ComponentType,
    "badge-groups:ModernLeadingError": d67.ModernLeadingError as ComponentType,
    "badge-groups:ModernLeadingWarning": d67.ModernLeadingWarning as ComponentType,
    "badge-groups:ModernLeadingSuccess": d67.ModernLeadingSuccess as ComponentType,
    "badge-groups:ModernTrailingGray": d67.ModernTrailingGray as ComponentType,
    "badge-groups:ModernTrailingBrand": d67.ModernTrailingBrand as ComponentType,
    "badge-groups:ModernTrailingError": d67.ModernTrailingError as ComponentType,
    "badge-groups:ModernTrailingWarning": d67.ModernTrailingWarning as ComponentType,
    "badge-groups:ModernTrailingSuccess": d67.ModernTrailingSuccess as ComponentType,
    "badges:BadgeExample": d68.BadgeExample as ComponentType,
    "badges:PillColor": d68.PillColor as ComponentType,
    "badges:Color": d68.Color as ComponentType,
    "badges:Modern": d68.Modern as ComponentType,
    "badges:WithDot": d68.WithDot as ComponentType,
    "badges:WithDotBadgeColor": d68.WithDotBadgeColor as ComponentType,
    "badges:WithDotBadgeModern": d68.WithDotBadgeModern as ComponentType,
    "badges:WithFlag": d68.WithFlag as ComponentType,
    "badges:WithFlagBadgeColor": d68.WithFlagBadgeColor as ComponentType,
    "badges:WithFlagBadgeModern": d68.WithFlagBadgeModern as ComponentType,
    "badges:WithAvatar": d68.WithAvatar as ComponentType,
    "badges:WithAvatarBadgeColor": d68.WithAvatarBadgeColor as ComponentType,
    "badges:WithAvatarBadgeModern": d68.WithAvatarBadgeModern as ComponentType,
    "badges:WithCloseX": d68.WithCloseX as ComponentType,
    "badges:WithCloseXBadgeColor": d68.WithCloseXBadgeColor as ComponentType,
    "badges:WithCloseXBadgeModern": d68.WithCloseXBadgeModern as ComponentType,
    "badges:WithIconLeading": d68.WithIconLeading as ComponentType,
    "badges:ColorWithIconLeading": d68.ColorWithIconLeading as ComponentType,
    "badges:ModernWithIconLeading": d68.ModernWithIconLeading as ComponentType,
    "badges:WithIconTrailing": d68.WithIconTrailing as ComponentType,
    "badges:ColorWithIconTrailing": d68.ColorWithIconTrailing as ComponentType,
    "badges:ModernWithIconTrailing": d68.ModernWithIconTrailing as ComponentType,
    "badges:WithIconOnly": d68.WithIconOnly as ComponentType,
    "badges:ColorWithIconOnly": d68.ColorWithIconOnly as ComponentType,
    "badges:ModernWithIconOnly": d68.ModernWithIconOnly as ComponentType,
    "button-group:ButtonGroupExample": d69.ButtonGroupExample as ComponentType,
    "button-group:LeadingIcon": d69.LeadingIcon as ComponentType,
    "button-group:WithDot": d69.WithDot as ComponentType,
    "button-group:Disabled": d69.Disabled as ComponentType,
    "button-group:DisabledIndividualItem": d69.DisabledIndividualItem as ComponentType,
    "button-group:Selection": d69.Selection as ComponentType,
    "button-group:MultipleSelection": d69.MultipleSelection as ComponentType,
    "app-store-buttons:MobileAppStoreButtonsExample": d70.MobileAppStoreButtonsExample as ComponentType,
    "app-store-buttons:GooglePlayButtons": d70.GooglePlayButtons as ComponentType,
    "app-store-buttons:AppStoreButtons": d70.AppStoreButtons as ComponentType,
    "app-store-buttons:GalaxyStoreButtons": d70.GalaxyStoreButtons as ComponentType,
    "app-store-buttons:AppGalleryButtons": d70.AppGalleryButtons as ComponentType,
    "app-store-buttons:GooglePlayOutlineButtons": d70.GooglePlayOutlineButtons as ComponentType,
    "app-store-buttons:AppStoreOutlineButtons": d70.AppStoreOutlineButtons as ComponentType,
    "app-store-buttons:GalaxyStoreOutlineButtons": d70.GalaxyStoreOutlineButtons as ComponentType,
    "app-store-buttons:AppGalleryOutlineButtons": d70.AppGalleryOutlineButtons as ComponentType,
    "button-utility:UtilityButtonsExample": d71.UtilityButtonsExample as ComponentType,
    "button-utility:Secondary": d71.Secondary as ComponentType,
    "button-utility:Tertiary": d71.Tertiary as ComponentType,
    "button-utility:Sizes": d71.Sizes as ComponentType,
    "button-utility:Disabled": d71.Disabled as ComponentType,
    "button-utility:CloseX": d71.CloseX as ComponentType,
    "button-utility:CloseXDark": d71.CloseXDark as ComponentType,
    "buttons:ButtonExample": d72.ButtonExample as ComponentType,
    "buttons:PrimaryButtons": d72.PrimaryButtons as ComponentType,
    "buttons:SecondaryButtons": d72.SecondaryButtons as ComponentType,
    "buttons:TertiaryButtons": d72.TertiaryButtons as ComponentType,
    "buttons:LinkColorButtonsExample": d72.LinkColorButtonsExample as ComponentType,
    "buttons:LinkGrayButtons": d72.LinkGrayButtons as ComponentType,
    "buttons:IconLeadingButtonsExample": d72.IconLeadingButtonsExample as ComponentType,
    "buttons:IconTrailingButtonsExample": d72.IconTrailingButtonsExample as ComponentType,
    "buttons:IconOnlyButtonsExample": d72.IconOnlyButtonsExample as ComponentType,
    "buttons:LoadingButtonsExample": d72.LoadingButtonsExample as ComponentType,
    "buttons:DisabledButtonsExample": d72.DisabledButtonsExample as ComponentType,
    "buttons:PrimaryButtonsDestructiveExample": d72.PrimaryButtonsDestructiveExample as ComponentType,
    "buttons:SecondaryButtonsDestructive": d72.SecondaryButtonsDestructive as ComponentType,
    "buttons:TertiaryButtonsDestructive": d72.TertiaryButtonsDestructive as ComponentType,
    "social-buttons:SocialButtonsExample": d73.SocialButtonsExample as ComponentType,
    "social-buttons:GoogleSocialButtons": d73.GoogleSocialButtons as ComponentType,
    "social-buttons:FacebookSocialButtons": d73.FacebookSocialButtons as ComponentType,
    "social-buttons:AppleSocialButtons": d73.AppleSocialButtons as ComponentType,
    "social-buttons:TwitterSocialButtons": d73.TwitterSocialButtons as ComponentType,
    "social-buttons:FigmaSocialButtons": d73.FigmaSocialButtons as ComponentType,
    "social-buttons:DribbleSocialButtons": d73.DribbleSocialButtons as ComponentType,
    "social-buttons:BrandSocialButtonsGroup": d73.BrandSocialButtonsGroup as ComponentType,
    "social-buttons:IconsBrandSocialButtonsGroup": d73.IconsBrandSocialButtonsGroup as ComponentType,
    "social-buttons:ColorSocialButtonsGroup": d73.ColorSocialButtonsGroup as ComponentType,
    "social-buttons:IconsColorSocialButtonsGroup": d73.IconsColorSocialButtonsGroup as ComponentType,
    "social-buttons:GraySocialButtonsGroup": d73.GraySocialButtonsGroup as ComponentType,
    "checkbox:CheckboxExample": d74.CheckboxExample as ComponentType,
    "checkbox:Base": d74.Base as ComponentType,
    "checkbox:WithLabel": d74.WithLabel as ComponentType,
    "checkbox:WithLabelAndHint": d74.WithLabelAndHint as ComponentType,
    "checkbox:Disabled": d74.Disabled as ComponentType,
    "checkbox:Sizes": d74.Sizes as ComponentType,
    "context-menus:ContextMenuExample": d75.ContextMenuExample as ComponentType,
    "context-menus:Simple": d75.Simple as ComponentType,
    "context-menus:Advanced": d75.Advanced as ComponentType,
    "dropdown:DropdownExample": d76.DropdownExample as ComponentType,
    "dropdown:ButtonSimple": d76.ButtonSimple as ComponentType,
    "dropdown:ButtonAdvanced": d76.ButtonAdvanced as ComponentType,
    "dropdown:ButtonLink": d76.ButtonLink as ComponentType,
    "dropdown:IconSimple": d76.IconSimple as ComponentType,
    "dropdown:IconAdvanced": d76.IconAdvanced as ComponentType,
    "dropdown:SearchSimple": d76.SearchSimple as ComponentType,
    "dropdown:SearchAdvanced": d76.SearchAdvanced as ComponentType,
    "dropdown:Integrations": d76.Integrations as ComponentType,
    "dropdown:AccountButton": d76.AccountButton as ComponentType,
    "dropdown:Avatar": d76.Avatar as ComponentType,
    "dropdown:AccountCardXs": d76.AccountCardXs as ComponentType,
    "dropdown:AccountCardSm": d76.AccountCardSm as ComponentType,
    "dropdown:AccountCardMd": d76.AccountCardMd as ComponentType,
    "dropdown:AccountBreadcrumb": d76.AccountBreadcrumb as ComponentType,
    "hover-card:HoverCardExample": d77.HoverCardExample as ComponentType,
    "hover-card:WithInteractiveContent": d77.WithInteractiveContent as ComponentType,
    "hover-card:Placements": d77.Placements as ComponentType,
    "hover-card:CustomDelays": d77.CustomDelays as ComponentType,
    "inputs:InputExample": d78.InputExample as ComponentType,
    "inputs:Default": d78.Default as ComponentType,
    "inputs:Disabled": d78.Disabled as ComponentType,
    "inputs:Invalid": d78.Invalid as ComponentType,
    "inputs:Sizes": d78.Sizes as ComponentType,
    "inputs:LeadingIcon": d78.LeadingIcon as ComponentType,
    "inputs:LeadingDropdown": d78.LeadingDropdown as ComponentType,
    "inputs:TrailingDropdown": d78.TrailingDropdown as ComponentType,
    "inputs:LeadingText": d78.LeadingText as ComponentType,
    "inputs:PaymentInput": d78.PaymentInput as ComponentType,
    "inputs:TrailingButton": d78.TrailingButton as ComponentType,
    "inputs:FileUpload": d78.FileUpload as ComponentType,
    "inputs:PasswordInput": d78.PasswordInput as ComponentType,
    "inputs:DateInput": d78.DateInput as ComponentType,
    "inputs:NumberInputHorizontal": d78.NumberInputHorizontal as ComponentType,
    "inputs:NumberInputVertical": d78.NumberInputVertical as ComponentType,
    "inputs:TagInput": d78.TagInput as ComponentType,
    "inputs:TagInputOuter": d78.TagInputOuter as ComponentType,
    "pin-input:VerificationCodeInputExample": d79.VerificationCodeInputExample as ComponentType,
    "pin-input:FourDigits": d79.FourDigits as ComponentType,
    "pin-input:WithSeparator": d79.WithSeparator as ComponentType,
    "pin-input:InputOTP": d79.InputOTP as ComponentType,
    "pin-input:Disabled": d79.Disabled as ComponentType,
    "pin-input:Sizes": d79.Sizes as ComponentType,
    "menubar:MenubarExample": d80.MenubarExample as ComponentType,
    "menubar:WithDisabledItems": d80.WithDisabledItems as ComponentType,
    "menubar:Minimal": d80.Minimal as ComponentType,
    "number-input:NumberInputExample": d81.NumberInputExample as ComponentType,
    "number-input:FormatOptions": d81.FormatOptions as ComponentType,
    "number-input:InlineButtons": d81.InlineButtons as ComponentType,
    "number-input:Sizes": d81.Sizes as ComponentType,
    "number-input:MinMaxStep": d81.MinMaxStep as ComponentType,
    "number-input:States": d81.States as ComponentType,
    "popover:PopoverExample": d82.PopoverExample as ComponentType,
    "popover:Placements": d82.Placements as ComponentType,
    "popover:WithIconTrigger": d82.WithIconTrigger as ComponentType,
    "progress-indicators:ProgressIndicatorExample": d83.ProgressIndicatorExample as ComponentType,
    "progress-indicators:Default": d83.Default as ComponentType,
    "progress-indicators:TextRight": d83.TextRight as ComponentType,
    "progress-indicators:TextBottom": d83.TextBottom as ComponentType,
    "progress-indicators:TextTopFloating": d83.TextTopFloating as ComponentType,
    "progress-indicators:TextBottomFloating": d83.TextBottomFloating as ComponentType,
    "progress-indicators:CircleProgressBar": d83.CircleProgressBar as ComponentType,
    "progress-indicators:CircleProgressBarLabel": d83.CircleProgressBarLabel as ComponentType,
    "progress-indicators:HalfCircleProgressBar": d83.HalfCircleProgressBar as ComponentType,
    "progress-indicators:HalfCircleProgressBarLabel": d83.HalfCircleProgressBarLabel as ComponentType,
    "radio-buttons:RadioButtonExample": d84.RadioButtonExample as ComponentType,
    "radio-buttons:WithLabel": d84.WithLabel as ComponentType,
    "radio-buttons:WithLabelAndHint": d84.WithLabelAndHint as ComponentType,
    "radio-buttons:Disabled": d84.Disabled as ComponentType,
    "radio-buttons:DisabledIndividualOption": d84.DisabledIndividualOption as ComponentType,
    "radio-buttons:Sizes": d84.Sizes as ComponentType,
    "radio-buttons:IconSimple": d84.IconSimple as ComponentType,
    "radio-buttons:IconCard": d84.IconCard as ComponentType,
    "radio-buttons:Avatar": d84.Avatar as ComponentType,
    "radio-buttons:PaymentIcon": d84.PaymentIcon as ComponentType,
    "radio-buttons:RadioButton": d84.RadioButton as ComponentType,
    "radio-buttons:Checkbox": d84.Checkbox as ComponentType,
    "multi-select:MultiSelectExample": d85.MultiSelectExample as ComponentType,
    "multi-select:Default": d85.Default as ComponentType,
    "multi-select:WithLeadingIcon": d85.WithLeadingIcon as ComponentType,
    "multi-select:Disabled": d85.Disabled as ComponentType,
    "multi-select:Sizes": d85.Sizes as ComponentType,
    "select:SelectExample": d86.SelectExample as ComponentType,
    "select:Default": d86.Default as ComponentType,
    "select:Disabled": d86.Disabled as ComponentType,
    "select:Sizes": d86.Sizes as ComponentType,
    "select:IconLeading": d86.IconLeading as ComponentType,
    "select:AvatarLeading": d86.AvatarLeading as ComponentType,
    "select:DotLeading": d86.DotLeading as ComponentType,
    "select:Search": d86.Search as ComponentType,
    "select:Tags": d86.Tags as ComponentType,
    "skeleton:SkeletonExample": d87.SkeletonExample as ComponentType,
    "skeleton:Avatar": d87.Avatar as ComponentType,
    "skeleton:TextBlock": d87.TextBlock as ComponentType,
    "skeleton:CardSkeleton": d87.CardSkeleton as ComponentType,
    "slider:SliderExample": d88.SliderExample as ComponentType,
    "slider:Default": d88.Default as ComponentType,
    "slider:BottomLabel": d88.BottomLabel as ComponentType,
    "slider:TopFloating": d88.TopFloating as ComponentType,
    "slider:SingleThumb": d88.SingleThumb as ComponentType,
    "tag-input:TagInputExample": d89.TagInputExample as ComponentType,
    "tag-input:Controlled": d89.Controlled as ComponentType,
    "tag-input:MaxTagsWithFeedback": d89.MaxTagsWithFeedback as ComponentType,
    "tag-input:WithValidation": d89.WithValidation as ComponentType,
    "tag-input:States": d89.States as ComponentType,
    "tags:TagsExample": d90.TagsExample as ComponentType,
    "tags:SizesExample": d90.SizesExample as ComponentType,
    "tags:CloseXExample": d90.CloseXExample as ComponentType,
    "tags:CountExample": d90.CountExample as ComponentType,
    "tags:CheckboxExample": d90.CheckboxExample as ComponentType,
    "tags:CheckboxCloseXExample": d90.CheckboxCloseXExample as ComponentType,
    "tags:CheckboxCountExample": d90.CheckboxCountExample as ComponentType,
    "text-editor:TextEditorExample": d91.TextEditorExample as ComponentType,
    "text-editor:DefaultSm": d91.DefaultSm as ComponentType,
    "text-editor:DefaultMd": d91.DefaultMd as ComponentType,
    "text-editor:FloatingToolbarSm": d91.FloatingToolbarSm as ComponentType,
    "text-editor:FloatingToolbarMd": d91.FloatingToolbarMd as ComponentType,
    "text-editor:WithTooltip": d91.WithTooltip as ComponentType,
    "textarea:TextareaExample": d92.TextareaExample as ComponentType,
    "textarea:Default": d92.Default as ComponentType,
    "textarea:Disabled": d92.Disabled as ComponentType,
    "textarea:Invalid": d92.Invalid as ComponentType,
    "toggle-chip:ToggleChipExample": d93.ToggleChipExample as ComponentType,
    "toggle-chip:Colors": d93.Colors as ComponentType,
    "toggle-chip:Sizes": d93.Sizes as ComponentType,
    "toggle-chip:FilterGroup": d93.FilterGroup as ComponentType,
    "toggle-chip:Disabled": d93.Disabled as ComponentType,
    "toggle:ToggleExample": d94.ToggleExample as ComponentType,
    "toggle:Base": d94.Base as ComponentType,
    "toggle:WithLabel": d94.WithLabel as ComponentType,
    "toggle:WithLabelAndHint": d94.WithLabelAndHint as ComponentType,
    "toggle:Disabled": d94.Disabled as ComponentType,
    "toggle:Sizes": d94.Sizes as ComponentType,
    "toggle:Slim": d94.Slim as ComponentType,
    "toggle:SlimWithLabelAndHint": d94.SlimWithLabelAndHint as ComponentType,
    "tooltip:TooltipExample": d95.TooltipExample as ComponentType,
    "tooltip:DefaultExample": d95.DefaultExample as ComponentType,
    "tooltip:WithArrowExample": d95.WithArrowExample as ComponentType,
    "tooltip:WithSupportingTextExample": d95.WithSupportingTextExample as ComponentType,
    "tooltip:PlacementsExample": d95.PlacementsExample as ComponentType,
    "video-player:VideoPlayerExample": d96.VideoPlayerExample as ComponentType,
    "video-player:VideoPlayerSm": d96.VideoPlayerSm as ComponentType,
    "video-player:VideoPlayerMd": d96.VideoPlayerMd as ComponentType,
    "video-player:VideoPlayerLg": d96.VideoPlayerLg as ComponentType,
    "featured-icon:FeaturedIconExample": d97.FeaturedIconExample as ComponentType,
    "featured-icon:Light": d97.Light as ComponentType,
    "featured-icon:Gradient": d97.Gradient as ComponentType,
    "featured-icon:Dark": d97.Dark as ComponentType,
    "featured-icon:Outline": d97.Outline as ComponentType,
    "featured-icon:Modern": d97.Modern as ComponentType,
    "featured-icon:ModernNeue": d97.ModernNeue as ComponentType,
    "rating:RatingBadgeExample": d98.RatingBadgeExample as ComponentType,
    "rating:RatingStarsExample": d98.RatingStarsExample as ComponentType,
    "typography:ArticleExample": d99.ArticleExample as ComponentType,
    "typography:Headings": d99.Headings as ComponentType,
    "typography:Images": d99.Images as ComponentType,
    "typography:QuoteDefault": d99.QuoteDefault as ComponentType,
    "typography:QuoteWithAvatar": d99.QuoteWithAvatar as ComponentType,
    "typography:QuoteCentered": d99.QuoteCentered as ComponentType,
    "typography:QuoteMinimal": d99.QuoteMinimal as ComponentType,
    "typography:InlineCode": d99.InlineCode as ComponentType,
    "typography:FeatureText": d99.FeatureText as ComponentType,
    "404-pages:Page404Example": d100.Page404Example as ComponentType,
    "about-pages:AboutPageExample": d101.AboutPageExample as ComponentType,
    "blog-pages:BlogExample": d102.BlogExample as ComponentType,
    "blog-post-pages:BlogPostExample": d103.BlogPostExample as ComponentType,
    "contact-pages:ContactPageExample": d104.ContactPageExample as ComponentType,
    "faq-pages:FAQPageExample": d105.FAQPageExample as ComponentType,
    "landing-pages:LandingPageExample": d106.LandingPageExample as ComponentType,
    "legal-pages:LegalPageExample": d107.LegalPageExample as ComponentType,
    "pricing-pages:PricingPageExample": d108.PricingPageExample as ComponentType,
    "team-pages:TeamPageExample": d109.TeamPageExample as ComponentType,
    "banners:BannerExample": d110.BannerExample as ComponentType,
    "blog-sections:BlogSectionExample": d111.BlogSectionExample as ComponentType,
    "careers-sections:CareersSectionExample": d112.CareersSectionExample as ComponentType,
    "contact-sections:ContactSectionExample": d113.ContactSectionExample as ComponentType,
    "content-rich-text-sections:ContentRichTextSectionExample": d114.ContentRichTextSectionExample as ComponentType,
    "cta-sections:CTASectionExample": d115.CTASectionExample as ComponentType,
    "faq-sections:FAQSectionExample": d116.FAQSectionExample as ComponentType,
    "features-sections:FeaturesSectionExample": d117.FeaturesSectionExample as ComponentType,
    "footers:FooterExample": d118.FooterExample as ComponentType,
    "header-navigations:HeaderNavigationExample": d119.HeaderNavigationExample as ComponentType,
    "header-sections:HeaderSectionExample": d120.HeaderSectionExample as ComponentType,
    "hero-header-sections:HeroHeaderSectionExample": d121.HeroHeaderSectionExample as ComponentType,
    "metrics-sections:MetricsSectionExample": d122.MetricsSectionExample as ComponentType,
    "newsletter-cta-sections:NewsletterCTASectionExample": d123.NewsletterCTASectionExample as ComponentType,
    "pricing-sections:PricingSectionExample": d124.PricingSectionExample as ComponentType,
    "social-proof-sections:SocialProofSectionExample": d125.SocialProofSectionExample as ComponentType,
    "team-sections:TeamSectionExample": d126.TeamSectionExample as ComponentType,
    "testimonial-sections:TestimonialsSectionExample": d127.TestimonialsSectionExample as ComponentType,
    "credit-card:CreditCardExample": d128.CreditCardExample as ComponentType,
    "credit-card:CustomizationExample": d128.CustomizationExample as ComponentType,
    "credit-card:SizesExample": d128.SizesExample as ComponentType,
    "credit-card:Transparent": d128.Transparent as ComponentType,
    "credit-card:TransparentGradient": d128.TransparentGradient as ComponentType,
    "credit-card:BrandDark": d128.BrandDark as ComponentType,
    "credit-card:BrandLight": d128.BrandLight as ComponentType,
    "credit-card:GrayDark": d128.GrayDark as ComponentType,
    "credit-card:GrayLight": d128.GrayLight as ComponentType,
    "credit-card:TransparentStrip": d128.TransparentStrip as ComponentType,
    "credit-card:GrayStrip": d128.GrayStrip as ComponentType,
    "credit-card:GradientStrip": d128.GradientStrip as ComponentType,
    "credit-card:SalmonStrip": d128.SalmonStrip as ComponentType,
    "credit-card:GrayStripVertical": d128.GrayStripVertical as ComponentType,
    "credit-card:GradientStripVertical": d128.GradientStripVertical as ComponentType,
    "credit-card:SalmonStripVertical": d128.SalmonStripVertical as ComponentType,
    "illustrations:IllustrationExample": d129.IllustrationExample as ComponentType,
    "illustrations:BoxSm": d129.BoxSm as ComponentType,
    "illustrations:BoxMd": d129.BoxMd as ComponentType,
    "illustrations:BoxLg": d129.BoxLg as ComponentType,
    "illustrations:CloudSm": d129.CloudSm as ComponentType,
    "illustrations:CloudMd": d129.CloudMd as ComponentType,
    "illustrations:CloudLg": d129.CloudLg as ComponentType,
    "illustrations:CreditCardSm": d129.CreditCardSm as ComponentType,
    "illustrations:CreditCardMd": d129.CreditCardMd as ComponentType,
    "illustrations:CreditCardLg": d129.CreditCardLg as ComponentType,
    "illustrations:DocumentsSm": d129.DocumentsSm as ComponentType,
    "illustrations:DocumentsMd": d129.DocumentsMd as ComponentType,
    "illustrations:DocumentsLg": d129.DocumentsLg as ComponentType,
    "qr-code:QRCodeExample": d130.QRCodeExample as ComponentType,
    "qr-code:DefaultExample": d130.DefaultExample as ComponentType,
    "qr-code:LargeExample": d130.LargeExample as ComponentType,
    "qr-code:WithGradientScanExample": d130.WithGradientScanExample as ComponentType,
    "qr-code:WithCustomOptionsExample": d130.WithCustomOptionsExample as ComponentType,
};
