// GENERATED FILE — do not edit by hand. Run `pnpm gen:nav`.
export type NavItem = { title: string; href: string };
export type NavGroup = { title: string; items: NavItem[]; collapsible?: boolean };

export const nav: NavGroup[] = [
    {
        title: "Documentation",
        items: [
            { title: "Accessibility", href: "/docs/accessibility" },
            { title: "Adopting Proper UI into an existing Tailwind app", href: "/docs/adopting" },
            { title: "AI agents & the Proper UI Skill", href: "/docs/agents" },
            { title: "CLI tool", href: "/docs/cli" },
            { title: "Dark mode", href: "/docs/dark-mode" },
            { title: "Icons", href: "/docs/icons" },
            { title: "Installation", href: "/docs/installation" },
            { title: "Introduction", href: "/docs/introduction" },
            { title: "Linting", href: "/docs/linting" },
            { title: "Quality", href: "/docs/quality" },
            { title: "Registry metadata for agents", href: "/docs/registry-metadata" },
            { title: "RTL support", href: "/docs/rtl" },
            { title: "Testing", href: "/docs/testing" },
            { title: "Theming", href: "/docs/theming" },
            { title: "Typography", href: "/docs/typography" },
            { title: "Upgrade guide", href: "/docs/upgrade" },
        ],
    },
    {
        title: "Integrations",
        items: [
            { title: "Bolt.new integration", href: "/integrations/bolt" },
            { title: "Claude Code integration", href: "/integrations/claude" },
            { title: "Codex integration", href: "/integrations/codex" },
            { title: "components.json", href: "/integrations/components-json" },
            { title: "Cursor integration", href: "/integrations/cursor" },
            { title: "Gemini integration", href: "/integrations/gemini" },
            { title: "Lovable integration", href: "/integrations/lovable" },
            { title: "MCP integration", href: "/integrations/mcp" },
            { title: "Monorepo integration", href: "/integrations/monorepo" },
            { title: "Next.js integration", href: "/integrations/nextjs" },
            { title: "Replit integration", href: "/integrations/replit" },
            { title: "shadcn CLI integration", href: "/integrations/shadcn" },
            { title: "v0 integration", href: "/integrations/v0" },
            { title: "Vite integration", href: "/integrations/vite" },
        ],
    },
    {
        title: "Base components",
        items: [
            { title: "404 sections", href: "/components/404-sections" },
            { title: "Activity feed components", href: "/components/activity-feeds" },
            { title: "Activity gauge components", href: "/components/activity-gauges" },
            { title: "AI elements", href: "/components/ai-elements" },
            { title: "Alert components", href: "/components/alerts" },
            { title: "Area chart components", href: "/components/area-charts" },
            { title: "Avatar components", href: "/components/avatars" },
            { title: "Badge components", href: "/components/badges" },
            { title: "Badge group components", href: "/components/badge-groups" },
            { title: "Breadcrumb components", href: "/components/breadcrumbs" },
            { title: "Button components", href: "/components/buttons" },
            { title: "Button group components", href: "/components/button-groups" },
            { title: "Calendar components", href: "/components/calendars" },
            { title: "Callout components", href: "/components/callouts" },
            { title: "Card header components", href: "/components/card-headers" },
            { title: "Carousel components", href: "/components/carousels" },
            { title: "Checkbox components", href: "/components/checkboxes" },
            { title: "Code editor components", href: "/components/code-editor" },
            { title: "Code snippet components", href: "/components/code-snippets" },
            { title: "Color picker components", href: "/components/color-pickers" },
            { title: "Combined chart components", href: "/components/combined-charts" },
            { title: "Command menu components", href: "/components/command-menus" },
            { title: "Confirm dialog components", href: "/components/confirm-dialogs" },
            { title: "Content divider components", href: "/components/content-dividers" },
            { title: "Context menu components", href: "/components/context-menus" },
            { title: "Credit card components", href: "/components/credit-cards" },
            { title: "Dashboards with header navigation", href: "/components/dashboards-02" },
            { title: "Dashboards with sidebar navigation", href: "/components/dashboards" },
            { title: "Data table", href: "/components/data-table" },
            { title: "Date picker components", href: "/components/date-pickers" },
            { title: "Description list components", href: "/components/description-lists" },
            { title: "Drawer components", href: "/components/drawers" },
            { title: "Dropdown components", href: "/components/dropdowns" },
            { title: "Email templates", href: "/components/email-templates" },
            { title: "Empty state components", href: "/components/empty-states" },
            { title: "Featured icon components", href: "/components/featured-icons" },
            { title: "File upload components", href: "/components/file-uploaders" },
            { title: "Filter bar components", href: "/components/filter-bars" },
            { title: "Forgot password pages", href: "/components/forgot-password-pages" },
            { title: "Gantt chart components", href: "/components/gantt" },
            { title: "Gradient picker components", href: "/components/gradient-pickers" },
            { title: "Header navigation components", href: "/components/header-navigations" },
            { title: "Hover card components", href: "/components/hover-card" },
            { title: "Illustration components", href: "/components/illustrations" },
            { title: "Image picker components", href: "/components/image-pickers" },
            { title: "Informational pages with header navigation", href: "/components/informational-pages-02" },
            { title: "Informational pages with sidebar navigation", href: "/components/informational-pages" },
            { title: "Inline CTA components", href: "/components/inline-ctas" },
            { title: "Input field", href: "/components/inputs" },
            { title: "Kanban board components", href: "/components/kanban-boards" },
            { title: "Line & bar chart components", href: "/components/line-bar-charts" },
            { title: "Loading indicator components", href: "/components/loading-indicators" },
            { title: "Log in pages", href: "/components/log-in-pages" },
            { title: "Menubar components", href: "/components/menubar" },
            { title: "Messaging components", href: "/components/messaging" },
            { title: "Metric components", href: "/components/metrics" },
            { title: "Mobile app store button components", href: "/components/mobile-app-store-buttons" },
            { title: "Modal components", href: "/components/modals" },
            { title: "Multi-select components", href: "/components/multi-select" },
            { title: "Notification components", href: "/components/notifications" },
            { title: "Number input components", href: "/components/number-input" },
            { title: "Page header components", href: "/components/page-headers" },
            { title: "Pagination components", href: "/components/pagination" },
            { title: "Pie chart components", href: "/components/pie-charts" },
            { title: "Popover components", href: "/components/popovers" },
            { title: "Progress indicator components", href: "/components/progress-indicators" },
            { title: "Progress steps components", href: "/components/progress-steps" },
            { title: "QR code components", href: "/components/qr-codes" },
            { title: "Radar chart components", href: "/components/radar-charts" },
            { title: "Radio button components", href: "/components/radio-buttons" },
            { title: "Radio group components", href: "/components/radio-groups" },
            { title: "Rating badge and stars", href: "/components/rating-badge-and-stars" },
            { title: "Resizable panel components", href: "/components/resizable-panels" },
            { title: "Scatter & bubble chart components", href: "/components/scatter-bubble-charts" },
            { title: "Scroll area components", href: "/components/scroll-areas" },
            { title: "Section footer components", href: "/components/section-footers" },
            { title: "Section header components", href: "/components/section-headers" },
            { title: "Select components", href: "/components/select" },
            { title: "Settings pages with header navigation", href: "/components/settings-pages-02" },
            { title: "Settings pages with sidebar navigation", href: "/components/settings-pages" },
            { title: "Sidebar navigation components", href: "/components/sidebar-navigations" },
            { title: "Sign up pages", href: "/components/sign-up-pages" },
            { title: "Skeleton components", href: "/components/skeleton" },
            { title: "Slider components", href: "/components/sliders" },
            { title: "Social button components", href: "/components/social-buttons" },
            { title: "Sortable list components", href: "/components/sortable-lists" },
            { title: "Sparkline components", href: "/components/sparklines" },
            { title: "Stepper components", href: "/components/stepper" },
            { title: "Tab components", href: "/components/tabs" },
            { title: "Table components", href: "/components/tables" },
            { title: "Tag components", href: "/components/tags" },
            { title: "Tag input components", href: "/components/tag-input" },
            { title: "Text editor components", href: "/components/text-editors" },
            { title: "Textarea input field", href: "/components/textareas" },
            { title: "Timeline components", href: "/components/timeline" },
            { title: "Toggle chip components", href: "/components/toggle-chips" },
            { title: "Toggle field components", href: "/components/toggles" },
            { title: "Tooltip components", href: "/components/tooltips" },
            { title: "Tree view components", href: "/components/tree-views" },
            { title: "Utility button components", href: "/components/utility-buttons" },
            { title: "Verification code input components", href: "/components/verification-code-inputs" },
            { title: "Verification pages", href: "/components/verification-pages" },
            { title: "Video player components", href: "/components/video-players" },
        ],
    },
    {
        title: "Application UI components",
        items: [
            { title: "404 sections", href: "/components/404-sections" },
            { title: "Activity feed components", href: "/components/activity-feeds" },
            { title: "Activity gauge components", href: "/components/activity-gauges" },
            { title: "AI elements", href: "/components/ai-elements" },
            { title: "Alert components", href: "/components/alerts" },
            { title: "Area chart components", href: "/components/area-charts" },
            { title: "Avatar components", href: "/components/avatars" },
            { title: "Badge components", href: "/components/badges" },
            { title: "Badge group components", href: "/components/badge-groups" },
            { title: "Breadcrumb components", href: "/components/breadcrumbs" },
            { title: "Button components", href: "/components/buttons" },
            { title: "Button group components", href: "/components/button-groups" },
            { title: "Calendar components", href: "/components/calendars" },
            { title: "Callout components", href: "/components/callouts" },
            { title: "Card header components", href: "/components/card-headers" },
            { title: "Carousel components", href: "/components/carousels" },
            { title: "Checkbox components", href: "/components/checkboxes" },
            { title: "Code editor components", href: "/components/code-editor" },
            { title: "Code snippet components", href: "/components/code-snippets" },
            { title: "Color picker components", href: "/components/color-pickers" },
            { title: "Combined chart components", href: "/components/combined-charts" },
            { title: "Command menu components", href: "/components/command-menus" },
            { title: "Confirm dialog components", href: "/components/confirm-dialogs" },
            { title: "Content divider components", href: "/components/content-dividers" },
            { title: "Context menu components", href: "/components/context-menus" },
            { title: "Credit card components", href: "/components/credit-cards" },
            { title: "Dashboards with header navigation", href: "/components/dashboards-02" },
            { title: "Dashboards with sidebar navigation", href: "/components/dashboards" },
            { title: "Data table", href: "/components/data-table" },
            { title: "Date picker components", href: "/components/date-pickers" },
            { title: "Description list components", href: "/components/description-lists" },
            { title: "Drawer components", href: "/components/drawers" },
            { title: "Dropdown components", href: "/components/dropdowns" },
            { title: "Email templates", href: "/components/email-templates" },
            { title: "Empty state components", href: "/components/empty-states" },
            { title: "Featured icon components", href: "/components/featured-icons" },
            { title: "File upload components", href: "/components/file-uploaders" },
            { title: "Filter bar components", href: "/components/filter-bars" },
            { title: "Forgot password pages", href: "/components/forgot-password-pages" },
            { title: "Gantt chart components", href: "/components/gantt" },
            { title: "Gradient picker components", href: "/components/gradient-pickers" },
            { title: "Header navigation components", href: "/components/header-navigations" },
            { title: "Hover card components", href: "/components/hover-card" },
            { title: "Illustration components", href: "/components/illustrations" },
            { title: "Image picker components", href: "/components/image-pickers" },
            { title: "Informational pages with header navigation", href: "/components/informational-pages-02" },
            { title: "Informational pages with sidebar navigation", href: "/components/informational-pages" },
            { title: "Inline CTA components", href: "/components/inline-ctas" },
            { title: "Input field", href: "/components/inputs" },
            { title: "Kanban board components", href: "/components/kanban-boards" },
            { title: "Line & bar chart components", href: "/components/line-bar-charts" },
            { title: "Loading indicator components", href: "/components/loading-indicators" },
            { title: "Log in pages", href: "/components/log-in-pages" },
            { title: "Menubar components", href: "/components/menubar" },
            { title: "Messaging components", href: "/components/messaging" },
            { title: "Metric components", href: "/components/metrics" },
            { title: "Mobile app store button components", href: "/components/mobile-app-store-buttons" },
            { title: "Modal components", href: "/components/modals" },
            { title: "Multi-select components", href: "/components/multi-select" },
            { title: "Notification components", href: "/components/notifications" },
            { title: "Number input components", href: "/components/number-input" },
            { title: "Page header components", href: "/components/page-headers" },
            { title: "Pagination components", href: "/components/pagination" },
            { title: "Pie chart components", href: "/components/pie-charts" },
            { title: "Popover components", href: "/components/popovers" },
            { title: "Progress indicator components", href: "/components/progress-indicators" },
            { title: "Progress steps components", href: "/components/progress-steps" },
            { title: "QR code components", href: "/components/qr-codes" },
            { title: "Radar chart components", href: "/components/radar-charts" },
            { title: "Radio button components", href: "/components/radio-buttons" },
            { title: "Radio group components", href: "/components/radio-groups" },
            { title: "Rating badge and stars", href: "/components/rating-badge-and-stars" },
            { title: "Resizable panel components", href: "/components/resizable-panels" },
            { title: "Scatter & bubble chart components", href: "/components/scatter-bubble-charts" },
            { title: "Scroll area components", href: "/components/scroll-areas" },
            { title: "Section footer components", href: "/components/section-footers" },
            { title: "Section header components", href: "/components/section-headers" },
            { title: "Select components", href: "/components/select" },
            { title: "Settings pages with header navigation", href: "/components/settings-pages-02" },
            { title: "Settings pages with sidebar navigation", href: "/components/settings-pages" },
            { title: "Sidebar navigation components", href: "/components/sidebar-navigations" },
            { title: "Sign up pages", href: "/components/sign-up-pages" },
            { title: "Skeleton components", href: "/components/skeleton" },
            { title: "Slider components", href: "/components/sliders" },
            { title: "Social button components", href: "/components/social-buttons" },
            { title: "Sortable list components", href: "/components/sortable-lists" },
            { title: "Sparkline components", href: "/components/sparklines" },
            { title: "Stepper components", href: "/components/stepper" },
            { title: "Tab components", href: "/components/tabs" },
            { title: "Table components", href: "/components/tables" },
            { title: "Tag components", href: "/components/tags" },
            { title: "Tag input components", href: "/components/tag-input" },
            { title: "Text editor components", href: "/components/text-editors" },
            { title: "Textarea input field", href: "/components/textareas" },
            { title: "Timeline components", href: "/components/timeline" },
            { title: "Toggle chip components", href: "/components/toggle-chips" },
            { title: "Toggle field components", href: "/components/toggles" },
            { title: "Tooltip components", href: "/components/tooltips" },
            { title: "Tree view components", href: "/components/tree-views" },
            { title: "Utility button components", href: "/components/utility-buttons" },
            { title: "Verification code input components", href: "/components/verification-code-inputs" },
            { title: "Verification pages", href: "/components/verification-pages" },
            { title: "Video player components", href: "/components/video-players" },
        ],
    },
    {
        title: "Marketing components",
        items: [
            { title: "404 pages", href: "/marketing/404-pages" },
            { title: "About pages", href: "/marketing/about-pages" },
            { title: "Banners", href: "/marketing/banners" },
            { title: "Blog posts", href: "/marketing/blog-post-pages" },
            { title: "Blog sections", href: "/marketing/blog-sections" },
            { title: "Blogs", href: "/marketing/blog-pages" },
            { title: "Careers sections", href: "/marketing/careers-sections" },
            { title: "Contact pages", href: "/marketing/contact-pages" },
            { title: "Contact sections", href: "/marketing/contact-sections" },
            { title: "Content rich text sections", href: "/marketing/content-rich-text-sections" },
            { title: "CTA sections", href: "/marketing/cta-sections" },
            { title: "FAQ pages", href: "/marketing/faq-pages" },
            { title: "FAQ sections", href: "/marketing/faq-sections" },
            { title: "Features sections", href: "/marketing/features-sections" },
            { title: "Footers", href: "/marketing/footers" },
            { title: "Header navigations", href: "/marketing/header-navigations" },
            { title: "Header sections", href: "/marketing/header-sections" },
            { title: "Hero header sections", href: "/marketing/hero-header-sections" },
            { title: "Landing pages", href: "/marketing/landing-pages" },
            { title: "Legal pages", href: "/marketing/legal-pages" },
            { title: "Metrics sections", href: "/marketing/metrics-sections" },
            { title: "Newsletter CTA sections", href: "/marketing/newsletter-cta-sections" },
            { title: "Pricing pages", href: "/marketing/pricing-pages" },
            { title: "Pricing sections", href: "/marketing/pricing-sections" },
            { title: "Social proof sections", href: "/marketing/social-proof-sections" },
            { title: "Team pages", href: "/marketing/team-pages" },
            { title: "Team sections", href: "/marketing/team-sections" },
            { title: "Testimonials sections", href: "/marketing/testimonial-sections" },
        ],
    },
];
