import type { ComponentType, ReactNode } from "react";
import { createElement } from "react";

/**
 * Hand-curated resolver for `<Playground component="…" />` (`~/components/playground.tsx`).
 *
 * Unlike `~/lib/demos.ts` (generated, one entry per demo export) this map is small and
 * hand-written on purpose: a playground renders the real, importable **component**, not a
 * demo export, so it needs a live `import()` of the library module plus enough knowledge of
 * that component's shape (does it take `children`, does it need fixed structural children
 * like `<Select.Item>`) to render one instance from arbitrary control values. Keys are
 * `"<registry slug>:<ExportName>"`, mirroring the `demoFile:Export` convention `demos.ts`
 * and `<Preview demo="…">` already use.
 *
 * Do not edit this file to "sync" it with `demos.ts` — it is not generated and is not meant
 * to cover every component, only the ones a docs page actually puts in a `<Playground>`.
 */

/** A resolved library module namespace, e.g. `import * as mod from "@properui/ui/components/base/buttons/button"`. */
type Module = Record<string, unknown>;

export type PlaygroundEntry = {
    /** Repo-relative import path shown (and used) in the generated snippet's import line. */
    importPath: string;
    /** The named export the snippet imports and instantiates. */
    exportName: string;
    /** Lazy-loads the module so `@properui/ui` is only pulled into the client bundle for pages that use it. */
    load: () => Promise<Module>;
    /** Renders one live instance from the resolved module and the playground's current control values. */
    render: (mod: Module, values: Record<string, unknown>) => ReactNode;
};

/** `<Component {...values} />` — correct for every curated component except the two below that need fixed structural children. */
const renderWithProps =
    (exportName: string) =>
    (mod: Module, values: Record<string, unknown>): ReactNode =>
        createElement(mod[exportName] as ComponentType<Record<string, unknown>>, values);

export const playgroundRegistry: Record<string, PlaygroundEntry> = {
    "buttons:Button": {
        importPath: "@properui/ui/components/base/buttons/button",
        exportName: "Button",
        load: () => import("@properui/ui/components/base/buttons/button"),
        render: renderWithProps("Button"),
    },
    "badges:Badge": {
        importPath: "@properui/ui/components/base/badges/badges",
        exportName: "Badge",
        load: () => import("@properui/ui/components/base/badges/badges"),
        render: renderWithProps("Badge"),
    },
    "input:Input": {
        importPath: "@properui/ui/components/base/input/input",
        exportName: "Input",
        load: () => import("@properui/ui/components/base/input/input"),
        render: renderWithProps("Input"),
    },
    "checkbox:Checkbox": {
        importPath: "@properui/ui/components/base/checkbox/checkbox",
        exportName: "Checkbox",
        load: () => import("@properui/ui/components/base/checkbox/checkbox"),
        render: renderWithProps("Checkbox"),
    },
    "toggle:Toggle": {
        importPath: "@properui/ui/components/base/toggle/toggle",
        exportName: "Toggle",
        load: () => import("@properui/ui/components/base/toggle/toggle"),
        render: renderWithProps("Toggle"),
    },
    "avatar:Avatar": {
        importPath: "@properui/ui/components/base/avatar/avatar",
        exportName: "Avatar",
        load: () => import("@properui/ui/components/base/avatar/avatar"),
        render: renderWithProps("Avatar"),
    },
    "slider:Slider": {
        importPath: "@properui/ui/components/base/slider/slider",
        exportName: "Slider",
        load: () => import("@properui/ui/components/base/slider/slider"),
        render: renderWithProps("Slider"),
    },
    "textarea:TextArea": {
        importPath: "@properui/ui/components/base/textarea/textarea",
        exportName: "TextArea",
        load: () => import("@properui/ui/components/base/textarea/textarea"),
        render: renderWithProps("TextArea"),
    },

    // `Select` requires structural `<Select.Item>` children the control panel has no way to
    // author, so a fixed set of options is rendered alongside whatever control values pick.
    "select:Select": {
        importPath: "@properui/ui/components/base/select/select",
        exportName: "Select",
        load: () => import("@properui/ui/components/base/select/select"),
        render: (mod, values) => {
            const Select = mod.Select as ComponentType<Record<string, unknown>> & { Item: ComponentType<Record<string, unknown>> };
            return createElement(
                Select,
                values,
                createElement(Select.Item, { key: "react", id: "react" }, "React"),
                createElement(Select.Item, { key: "vue", id: "vue" }, "Vue"),
                createElement(Select.Item, { key: "svelte", id: "svelte" }, "Svelte"),
            );
        },
    },

    // `Tooltip`'s `children` is the trigger element it attaches hover/focus handling to, not
    // text content, so a fixed trigger button is rendered and the control values become the
    // tooltip's own props (`title`, `placement`, …).
    "tooltip:Tooltip": {
        importPath: "@properui/ui/components/base/tooltip/tooltip",
        exportName: "Tooltip",
        load: () => import("@properui/ui/components/base/tooltip/tooltip"),
        render: (mod, values) => {
            const Tooltip = mod.Tooltip as ComponentType<Record<string, unknown>>;
            const TooltipTrigger = mod.TooltipTrigger as ComponentType<{ children?: ReactNode }>;
            return createElement(Tooltip, values, createElement(TooltipTrigger, {}, "Hover me"));
        },
    },
};

export type PlaygroundKey = keyof typeof playgroundRegistry;
